/**
 * Trekora SEO + tagging master taxonomy.
 * Used for metadata, filters, gallery, reviews, sitemap helpers, and recommendations.
 * UI-facing trek `tags` in treks.ts stay unchanged; this layer is search/SEO-specific.
 */

export interface ProductSEOProfile {
  slug: string;
  tags: string[];
  seoKeywords: string[];
  difficulty?: string;
  season?: string[];
  activities?: string[];
  terrain?: string[];
  states?: string[];
  altitudeCategory?: string;
  experienceType?: string[];
  travelStyle?: string[];
}

/** Gallery system tags */
export const GALLERY_SEO_TAGS = [
  "trek photos",
  "himalayan photography",
  "trekking memories",
  "mountain landscapes",
  "traveler gallery",
  "trekora gallery",
  "adventure photos",
  "camping memories",
  "summit photos",
  "snowfall gallery",
  "trekking reels",
  "yatra moments",
] as const;

export const ACTIVITY_SEO_TAGS = [
  "trekking",
  "hiking",
  "camping",
  "backpacking",
  "snow trekking",
  "mountaineering",
  "summit climb",
  "river crossing",
  "glacier trekking",
  "spiritual tourism",
  "photography",
  "adventure sports",
  "mountain travel",
  "nature exploration",
  "wildlife tourism",
] as const;

export const SEASONAL_SEO_TAGS = {
  winter: [
    "winter trek",
    "snowfall trek",
    "snow camping",
    "frozen lakes",
    "winter adventure",
  ],
  summer: ["summer trek", "green valley trek", "himalayan summer"],
  monsoon: ["monsoon trek", "valley flowers", "lush mountains", "waterfall trek"],
  autumn: ["autumn trekking", "clear mountain views", "scenic landscapes"],
} as const;

export const GEO_SEO_TAGS = [
  "uttarakhand",
  "himachal pradesh",
  "kashmir",
  "ladakh",
  "sikkim",
  "nepal",
  "himalayas",
  "indian himalayas",
  "north india travel",
] as const;

export const HIGH_CONVERSION_SEO_KEYWORDS = [
  "best trekking company in india",
  "best travel company for treks",
  "affordable trekking packages india",
  "premium trekking experience",
  "best himalayan trekking company",
  "trekking packages from delhi",
  "trekking tours india",
  "himalayan adventures india",
  "mountain travel company",
  "trekking booking website",
  "trusted trekking company india",
  "best travel platform india",
  "adventure tourism india",
  "trek booking online",
  "hiking tours india",
  "trekking website india",
  "backpacking india tours",
  "group trekking tours india",
  "trekking and camping india",
  "indian mountain adventures",
] as const;

export const TREKORA_BRAND_KEYWORDS = [
  "trekora",
  "trekora india",
  "trekora trekking",
  "trekora adventures",
  "trekora travel",
  "trekora trekking company",
  "trekora yatra packages",
  "trekora travel platform",
  "trekora reviews",
  "trekora gallery",
  "trekora booking",
  "trekora packages",
  "trekora mountain adventures",
  "trekora hiking tours",
  "trekora himalayas",
] as const;

export const LONG_TAIL_SEO_KEYWORDS = [
  "best winter trek for beginners in india",
  "affordable snow trekking packages india",
  "best trekking company for himalayan treks",
  "valley of flowers guided trekking package",
  "kedarnath yatra package from delhi",
  "best monsoon trekking destinations india",
  "top himalayan trekking packages 2026",
  "trekking packages with camping india",
  "scenic mountain trekking tours india",
  "trekking and photography tours india",
  "family friendly trekking packages india",
  "beginner friendly himalayan treks",
  "best travel website for trekking packages",
  "safe trekking company in india",
  "guided trekking tours with meals",
  "best trekking experience in uttarakhand",
  "himachal trekking package with camping",
  "premium trekking and travel experiences",
  "solo traveler trekking groups india",
  "adventure tourism packages india",
] as const;

export const PACKAGE_SEO_PROFILES = {
  adventure: {
    tags: [
      "adventure package",
      "trekking package",
      "himalayan package",
      "backpacking india",
      "mountain expedition",
      "travel experience",
      "camping adventure",
      "outdoor package",
    ],
    seoKeywords: [
      "best trekking packages india",
      "adventure travel packages india",
      "himalayan trekking packages",
      "affordable trekking packages",
      "group trekking packages",
      "premium trekking tours",
      "travel packages for trekkers",
    ],
  },
  luxury: {
    tags: [
      "luxury travel",
      "premium package",
      "luxury trek",
      "premium camping",
      "luxury himalayan tour",
      "curated experiences",
      "private travel",
    ],
    seoKeywords: [
      "luxury trekking packages india",
      "premium himalayan tours",
      "luxury travel india",
      "premium trekking company india",
    ],
  },
} as const;

/** Curated per-product SEO (extends static trek/yatra records). */
export const TREK_SEO_BY_SLUG: Record<string, ProductSEOProfile> = {
  "kedarkantha-trek": {
    slug: "kedarkantha-trek",
    tags: [
      "kedarkantha",
      "kedarkantha trek",
      "kedarkantha winter trek",
      "snow trek",
      "beginner trek",
      "uttarakhand trek",
      "summit trek",
      "camping trek",
      "himalayan trek",
      "winter adventure",
      "pine forest",
      "mountain camping",
      "snowfall trek",
      "solo trekking",
      "group trekking",
      "photography trek",
      "december trek",
      "january trek",
      "scenic trek",
      "high altitude trek",
    ],
    seoKeywords: [
      "best winter trek in india",
      "kedarkantha trek package",
      "kedarkantha trek booking",
      "kedarkantha trek itinerary",
      "kedarkantha trek price",
      "kedarkantha trek from delhi",
      "kedarkantha trek difficulty",
      "kedarkantha trek snowfall",
      "kedarkantha trek review",
      "kedarkantha trek photos",
      "kedarkantha trek gallery",
      "kedarkantha trek best time",
      "affordable himalayan trek",
      "beginner himalayan trek india",
      "snow trekking india",
      "top winter treks india",
    ],
    difficulty: "Easy-Moderate",
    season: ["winter"],
    activities: ["snow trekking", "camping", "summit climb", "photography"],
    terrain: ["pine forest", "snow"],
    states: ["uttarakhand"],
    altitudeCategory: "3000m+",
    experienceType: ["beginner friendly", "summit experience"],
    travelStyle: ["group trekking", "camping trek"],
  },
  "valley-of-flowers": {
    slug: "valley-of-flowers",
    tags: [
      "valley of flowers",
      "valley of flowers trek",
      "flower valley trek",
      "unesco site",
      "alpine flowers",
      "monsoon trek",
      "uttarakhand trekking",
      "scenic valley",
      "nature photography",
      "floral landscape",
      "beginner trek",
      "valley adventure",
      "eco tourism",
      "mountain flowers",
      "himalayan biodiversity",
    ],
    seoKeywords: [
      "valley of flowers trek package",
      "valley of flowers trek booking",
      "valley of flowers national park",
      "best monsoon trek india",
      "valley of flowers photos",
      "valley of flowers travel guide",
      "valley of flowers itinerary",
      "valley of flowers trekking cost",
      "valley of flowers review",
      "valley of flowers from delhi",
      "best flower valley trek india",
      "unesco trekking destination india",
    ],
    difficulty: "Easy-Moderate",
    season: ["monsoon", "summer"],
    activities: ["trekking", "photography", "nature exploration"],
    terrain: ["valley", "alpine meadow"],
    states: ["uttarakhand"],
    altitudeCategory: "3000m+",
    experienceType: ["beginner friendly", "nature trek"],
    travelStyle: ["guided trekking"],
  },
  "roopkund-trek": {
    slug: "roopkund-trek",
    tags: [
      "roopkund",
      "skeleton lake",
      "mystery lake",
      "roopkund trek",
      "challenging trek",
      "high altitude trek",
      "glacier trek",
      "himalayan adventure",
      "uttarakhand trek",
      "alpine camping",
      "summit trail",
      "adventure expedition",
    ],
    seoKeywords: [
      "roopkund trek package",
      "roopkund trek booking",
      "skeleton lake trek india",
      "roopkund trek itinerary",
      "roopkund trek photos",
      "roopkund trek difficulty",
      "best mystery trek india",
      "roopkund trekking guide",
      "roopkund trek review",
      "roopkund travel package",
    ],
    difficulty: "Moderate-Difficult",
    season: ["summer", "autumn"],
    activities: ["glacier trekking", "camping", "summit climb"],
    terrain: ["glacier", "alpine meadow"],
    states: ["uttarakhand"],
    altitudeCategory: "5000m+",
    experienceType: ["challenging", "expedition"],
    travelStyle: ["adventure expedition"],
  },
  "hampta-pass": {
    slug: "hampta-pass",
    tags: [
      "hampta pass",
      "crossover trek",
      "himachal trek",
      "valley crossing",
      "river crossing",
      "camping trek",
      "dramatic landscapes",
      "glacier views",
      "summer trek",
      "monsoon trek",
    ],
    seoKeywords: [
      "hampta pass trek package",
      "hampta pass trek booking",
      "hampta pass trek review",
      "hampta pass trek best time",
      "hampta pass trek from delhi",
      "best crossover trek india",
      "himachal trekking package",
      "adventure trek himachal",
    ],
    difficulty: "Moderate",
    season: ["summer", "monsoon"],
    activities: ["river crossing", "camping", "trekking"],
    terrain: ["valley", "pass"],
    states: ["himachal pradesh"],
    altitudeCategory: "4000m+",
    experienceType: ["crossover trek"],
    travelStyle: ["camping trek"],
  },
  "brahmatal-trek": {
    slug: "brahmatal-trek",
    tags: [
      "brahmatal",
      "brahmatal trek",
      "frozen lake",
      "snow trek",
      "winter trek",
      "uttarakhand adventure",
      "beginner winter trek",
      "summit trekking",
      "alpine camping",
    ],
    seoKeywords: [
      "brahmatal trek package",
      "brahmatal trek booking",
      "brahmatal trek review",
      "brahmatal trek photos",
      "brahmatal trek snowfall",
      "best winter trek uttarakhand",
    ],
    difficulty: "Easy-Moderate",
    season: ["winter"],
    activities: ["snow trekking", "camping", "summit climb"],
    terrain: ["frozen lake", "snow"],
    states: ["uttarakhand"],
    altitudeCategory: "3000m+",
    experienceType: ["beginner winter trek"],
    travelStyle: ["camping trek"],
  },
};

export const YATRA_SEO_BY_SLUG: Record<string, ProductSEOProfile> = {
  "kedarnath-yatra": {
    slug: "kedarnath-yatra",
    tags: [
      "kedarnath yatra",
      "kedarnath temple",
      "char dham",
      "shiva temple",
      "spiritual travel",
      "himalayan pilgrimage",
      "uttarakhand pilgrimage",
      "jyotirlinga",
      "religious tourism",
      "mountain temple",
    ],
    seoKeywords: [
      "kedarnath yatra package",
      "kedarnath helicopter booking",
      "kedarnath yatra registration",
      "kedarnath travel guide",
      "kedarnath temple booking",
      "kedarnath package from delhi",
      "best kedarnath travel company",
      "kedarnath yatra review",
    ],
    season: ["summer", "autumn"],
    activities: ["spiritual tourism", "mountain travel"],
    states: ["uttarakhand"],
    experienceType: ["pilgrimage"],
    travelStyle: ["group pilgrimage"],
  },
  "badrinath-yatra": {
    slug: "badrinath-yatra",
    tags: [
      "badrinath yatra",
      "badrinath temple",
      "char dham yatra",
      "spiritual journey",
      "pilgrimage tour",
      "uttarakhand temple",
      "religious travel",
      "himalayan temple",
    ],
    seoKeywords: [
      "badrinath yatra package",
      "badrinath booking",
      "badrinath travel package",
      "char dham package india",
      "badrinath trip from delhi",
    ],
    season: ["summer", "autumn"],
    activities: ["spiritual tourism"],
    states: ["uttarakhand"],
    experienceType: ["pilgrimage"],
    travelStyle: ["pilgrimage tour"],
  },
};
