import List "mo:core/List";
import Map "mo:core/Map";
import Time "mo:core/Time";


import TrekLib "lib/trek";
import YatraLib "lib/yatra";
import BookingLib "lib/booking";
import LeadQueryLib "lib/leadquery";
import UserLib "lib/user";
import BlogLib "lib/blog";
import PromoLib "lib/promo";
import BatchLib "lib/batch";
import TrekApi "mixins/trek-api";
import YatraApi "mixins/yatra-api";
import BookingApi "mixins/booking-api";
import QueryApi "mixins/query-api";
import UserApi "mixins/user-api";
import BlogApi "mixins/blog-api";
import PromoApi "mixins/promo-api";
import BatchApi "mixins/batch-api";
import TrekTypes "types/trek";
import YatraTypes "types/yatra";
import Common "types/common";
import UgcLib "lib/ugc";
import TrailLib "lib/trail";
import UgcApi "mixins/ugc-api";
import TrailApi "mixins/trail-api";
import TrailTypes "types/trail";
import Persistence "lib/persistence";
import Principal "mo:core/Principal";
import AdminApi "mixins/admin-api";


actor {
  // ── Stable storage (persisted across canister upgrades) ──────────────────
  stable var stableTreks : [TrekLib.Trek] = [];
  stable var stableYatras : [YatraLib.Yatra] = [];
  stable var stableBookings : [BookingLib.Booking] = [];
  stable var stableQueries : [LeadQueryLib.LeadQuery] = [];
  stable var stableBlogs : [BlogLib.BlogPost] = [];
  stable var stableBatches : [BatchLib.TrekBatch] = [];
  stable var stableUgcPhotos : [UgcLib.UgcPhoto] = [];
  stable var stableAdmins : [Principal] = [];
  stable var stableProfiles : [(Principal, UserLib.UserProfile)] = [];
  stable var stablePromos : [(Text, PromoLib.PromoCode)] = [];
  stable var stableWeatherCache : [(Text, Common.WeatherCache)] = [];
  stable var stableTrailConditions : [(Text, TrailLib.TrailCondition)] = [];
  stable var stableTrekCounter : Nat = 1;
  stable var stableYatraCounter : Nat = 1;
  stable var stableBookingCounter : Nat = 1;
  stable var stableQueryCounter : Nat = 1;
  stable var stableBlogCounter : Nat = 1;
  stable var stableBatchCounter : Nat = 1;
  stable var stableUgcCounter : Nat = 1;
  stable var stableSeedDone : Bool = false;

  // ── Runtime state (rehydrated from stable vars) ────────────────────────────
  var treks = Persistence.listFromArray(stableTreks);
  var trekCounter : Common.Counter = { var value = stableTrekCounter };

  var yatras = Persistence.listFromArray(stableYatras);
  var yatraCounter : Common.Counter = { var value = stableYatraCounter };

  var bookings = Persistence.listFromArray(stableBookings);
  var bookingCounter : Common.Counter = { var value = stableBookingCounter };

  var queries = Persistence.listFromArray(stableQueries);
  var queryCounter : Common.Counter = { var value = stableQueryCounter };

  var profiles = Persistence.mapFromEntries(stableProfiles);
  var blogs = Persistence.listFromArray(stableBlogs);
  var blogCounter : Common.Counter = { var value = stableBlogCounter };

  var promos = Persistence.mapFromEntries(stablePromos);
  var batches = Persistence.listFromArray(stableBatches);
  var batchCounter : Common.Counter = { var value = stableBatchCounter };

  var admins = Persistence.principalsFromArray(stableAdmins);

  var weatherCache = Persistence.mapFromEntries(stableWeatherCache);
  var ugcPhotos = Persistence.listFromArray(stableUgcPhotos);
  var ugcCounter : Common.Counter = { var value = stableUgcCounter };

  var trailConditions = Persistence.mapFromEntries(stableTrailConditions);
  var seedDone : Bool = stableSeedDone;

  system func preupgrade() {
    stableTreks := Persistence.listToArray(treks);
    stableYatras := Persistence.listToArray(yatras);
    stableBookings := Persistence.listToArray(bookings);
    stableQueries := Persistence.listToArray(queries);
    stableBlogs := Persistence.listToArray(blogs);
    stableBatches := Persistence.listToArray(batches);
    stableUgcPhotos := Persistence.listToArray(ugcPhotos);
    stableAdmins := Persistence.principalsToArray(admins);
    stableProfiles := Persistence.mapToEntries(profiles);
    stablePromos := Persistence.mapToEntries(promos);
    stableWeatherCache := Persistence.mapToEntries(weatherCache);
    stableTrailConditions := Persistence.mapToEntries(trailConditions);
    stableTrekCounter := trekCounter.value;
    stableYatraCounter := yatraCounter.value;
    stableBookingCounter := bookingCounter.value;
    stableQueryCounter := queryCounter.value;
    stableBlogCounter := blogCounter.value;
    stableBatchCounter := batchCounter.value;
    stableUgcCounter := ugcCounter.value;
    stableSeedDone := seedDone;
  };

  system func postupgrade() {
    treks := Persistence.listFromArray(stableTreks);
    trekCounter := { var value = stableTrekCounter };
    yatras := Persistence.listFromArray(stableYatras);
    yatraCounter := { var value = stableYatraCounter };
    bookings := Persistence.listFromArray(stableBookings);
    bookingCounter := { var value = stableBookingCounter };
    queries := Persistence.listFromArray(stableQueries);
    queryCounter := { var value = stableQueryCounter };
    profiles := Persistence.mapFromEntries(stableProfiles);
    blogs := Persistence.listFromArray(stableBlogs);
    blogCounter := { var value = stableBlogCounter };
    promos := Persistence.mapFromEntries(stablePromos);
    batches := Persistence.listFromArray(stableBatches);
    batchCounter := { var value = stableBatchCounter };
    admins := Persistence.principalsFromArray(stableAdmins);
    weatherCache := Persistence.mapFromEntries(stableWeatherCache);
    ugcPhotos := Persistence.listFromArray(stableUgcPhotos);
    ugcCounter := { var value = stableUgcCounter };
    trailConditions := Persistence.mapFromEntries(stableTrailConditions);
    seedDone := stableSeedDone;
  };

  func unsplash(photoId : Text) : Text {
    "https://images.unsplash.com/" # photoId # "?w=1200&q=80"
  };

  func seedTreks() {
    let uttarakhandTreks : [TrekTypes.TrekInput] = [
      { name = "Roopkund Trek"; slug = "roopkund-trek"; state = "Uttarakhand"; duration = 8; altitude = 5029; difficulty = "Moderate-Difficult"; price = 12000; rating = 4.8; reviewCount = 342; description = "Roopkund Trek, also known as the Skeleton Lake trek, is one of the most mysterious and fascinating treks in India. Located in the Chamoli district of Uttarakhand, this high-altitude glacial lake sits at an elevation of 5,029m. The lake is famous for the hundreds of ancient human skeletons found at its rim, believed to be from the 9th century AD. The trek passes through dense forests, beautiful meadows of Bedni Bugyal and Ali Bugyal, and offers stunning views of Trishul (7,120m) and Nanda Ghunti peaks."; image = unsplash("photo-1558618666-fcd25c85cd64"); images = [unsplash("photo-1558618666-fcd25c85cd64"), unsplash("photo-1501854140801-50d01698950b"), unsplash("photo-1486325212027-8081e485255e")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 53; startPoint = "Lohajung"; endPoint = "Lohajung"; trekType = "Snow/Alpine"; isActive = true; isFeatured = true },
      { name = "Valley of Flowers"; slug = "valley-of-flowers"; state = "Uttarakhand"; duration = 6; altitude = 3858; difficulty = "Easy-Moderate"; price = 8500; rating = 4.9; reviewCount = 521; description = "The Valley of Flowers is a UNESCO World Heritage Site in the Chamoli district of Uttarakhand. It's a vast meadow of alpine flowers nestled between the majestic Himalayan peaks. During the monsoon season (July-September), over 300 species of wildflowers bloom here, creating a breathtaking carpet of color. The valley is also home to rare wildlife including Snow Leopard, Asiatic Black Bear, and the Blue Sheep. The trek starts from Govindghat and passes through Ghangaria, making it accessible to most fitness levels."; image = unsplash("photo-1506905925346-21bda4d32df4"); images = [unsplash("photo-1506905925346-21bda4d32df4"), unsplash("photo-1464278533981-50106e6176b1"), unsplash("photo-1516912481808-3406841bd33c")]; category = "Trek"; bestSeason = "Jul-Sep"; distance = 38; startPoint = "Govindghat"; endPoint = "Govindghat"; trekType = "Alpine/Flower"; isActive = true; isFeatured = true },
      { name = "Kedarnath Trek"; slug = "kedarnath-trek"; state = "Uttarakhand"; duration = 4; altitude = 3583; difficulty = "Easy"; price = 6500; rating = 4.7; reviewCount = 890; description = "The Kedarnath Trek is one of the most sacred pilgrimages in India, leading to the ancient Kedarnath Temple dedicated to Lord Shiva. Located in the Rudraprayag district of Uttarakhand, this trek combines spiritual significance with stunning mountain scenery. The trail passes through dense forests, river crossings, and opens up to dramatic mountain vistas. The temple itself is set against the imposing Kedarnath peak (6,940m), making it one of the most spectacular settings of any religious site in the world."; image = unsplash("photo-1545558014-8692077e9b5c"); images = [unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1609766418204-94aaeaf0f4b7"), unsplash("photo-1473445730015-841f29a9490b")]; category = "Trek/Yatra"; bestSeason = "May-Jun, Sep-Oct"; distance = 32; startPoint = "Gaurikund"; endPoint = "Gaurikund"; trekType = "Pilgrimage/Forest"; isActive = true; isFeatured = true },
      { name = "Chopta Tungnath Chandrashila Trek"; slug = "chopta-tungnath"; state = "Uttarakhand"; duration = 5; altitude = 4090; difficulty = "Easy-Moderate"; price = 7200; rating = 4.8; reviewCount = 356; description = "The Chopta–Tungnath–Chandrashila circuit in Rudraprayag district is one of Uttarakhand's most rewarding short Himalayan journeys. From Chopta (~2,680m) a 3.5–4km trail climbs through rhododendron forest to Tungnath (~3,680m), the world's highest Shiva temple and part of Panch Kedar. A further 1–1.5km ridge leads to Chandrashila (~4,000m) for 360° views of Chaukhamba, Kedarnath, Nanda Devi, and Trishul. Round trip walking from Chopta is about 10–11km; winter brings snow — carry spikes and warm layers. Most itineraries add road transfer from Rishikesh, acclimatisation at Chopta, and a pre-dawn summit for sunrise."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1778761819/yjshqdmosaynlogonssx.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1778761819/yjshqdmosaynlogonssx.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778761836/rw2hjzozae9xd9ooloce.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778761847/w4uxnxm08dbffikt8ghs.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778761864/znomwlytytdgvzrb9mec.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778761881/neiz4dgf089bgstrra1c.jpg"]; category = "Trek"; bestSeason = "Mar-Jun, Sep-Nov, Dec-Mar"; distance = 11; startPoint = "Chopta"; endPoint = "Chopta"; trekType = "Pilgrimage/Summit"; isActive = true; isFeatured = false },
      { name = "Har Ki Dun"; slug = "har-ki-dun"; state = "Uttarakhand"; duration = 7; altitude = 3566; difficulty = "Moderate"; price = 10500; rating = 4.7; reviewCount = 198; description = "Har Ki Dun, meaning 'Valley of Gods', is a cradle-shaped hanging valley in the Garhwal Himalayas. This ancient trade route to Tibet passes through pristine forests of oak, rhododendron, and pine, meandering alongside the Tons River. The valley is dotted with quaint villages that have preserved their ancient culture for centuries. The surrounding peaks of Swargarohini (6,252m) and Bandarpunch (6,316m) create a stunning backdrop."; image = unsplash("photo-1464822759023-fed622ff2c3b"); images = [unsplash("photo-1464822759023-fed622ff2c3b"), unsplash("photo-1501854140801-50d01698950b"), unsplash("photo-1508193638397-1c4234db14d8")]; category = "Trek"; bestSeason = "Apr-Jun, Sep-Nov"; distance = 47; startPoint = "Sankri"; endPoint = "Sankri"; trekType = "Forest/Valley"; isActive = true; isFeatured = true },
      { name = "Brahmatal Trek"; slug = "brahmatal-trek"; state = "Uttarakhand"; duration = 6; altitude = 3861; difficulty = "Moderate"; price = 9500; rating = 4.8; reviewCount = 234; description = "Brahmatal Trek is one of the finest winter treks in India, renowned for its spectacular views of Mt. Trishul and Mt. Nanda Ghunti reflected in the frozen Brahmatal lake. Situated in the Chamoli district, this trek passes through thick oak and rhododendron forests draped in snow, open meadows, and a frozen lake at the summit. According to Hindu mythology, Lord Brahma meditated at Brahmatal, giving the lake its name."; image = unsplash("photo-1519681393784-d120267933ba"); images = [unsplash("photo-1519681393784-d120267933ba"), unsplash("photo-1558618666-fcd25c85cd64"), unsplash("photo-1473445730015-841f29a9490b")]; category = "Trek"; bestSeason = "Dec-Mar"; distance = 35; startPoint = "Lohajung"; endPoint = "Lohajung"; trekType = "Snow/Winter"; isActive = true; isFeatured = false },
      { name = "Kedarkantha Trek"; slug = "kedarkantha-trek"; state = "Uttarakhand"; duration = 6; altitude = 3810; difficulty = "Easy-Moderate"; price = 8500; rating = 4.9; reviewCount = 567; description = "Kedarkantha is India's most popular winter trek, offering a perfect introduction to snow trekking. Starting from the quaint village of Sankri in Uttarkashi, the trek winds through beautiful forests of pine, oak, and rhododendron to reach a stunning summit with panoramic views of over 13 Himalayan peaks. The mountain camping in snow makes this trek an unforgettable experience for first-time trekkers."; image = unsplash("photo-1551632811-561732d1e306"); images = [unsplash("photo-1551632811-561732d1e306"), unsplash("photo-1519681393784-d120267933ba"), unsplash("photo-1516912481808-3406841bd33c")]; category = "Trek"; bestSeason = "Dec-Apr"; distance = 22; startPoint = "Sankri"; endPoint = "Sankri"; trekType = "Snow/Winter"; isActive = true; isFeatured = true },
      { name = "Dayara Bugyal"; slug = "dayara-bugyal"; state = "Uttarakhand"; duration = 5; altitude = 3408; difficulty = "Easy"; price = 7500; rating = 4.7; reviewCount = 156; description = "Dayara Bugyal is one of the most beautiful alpine meadows in Uttarakhand, known for its lush green pastures in summer and snow-covered slopes in winter. The word 'Bugyal' means high-altitude meadow in the local Garhwali language. The trek offers spectacular views of Bandarpunch (6,316m), Black Peak (6,387m), Srikanth (6,133m), and Draupadi Ka Danda peaks. The meadow transforms into a surreal winter wonderland between December and March."; image = unsplash("photo-1516912481808-3406841bd33c"); images = [unsplash("photo-1516912481808-3406841bd33c"), unsplash("photo-1551632811-561732d1e306"), unsplash("photo-1464822759023-fed622ff2c3b")]; category = "Trek"; bestSeason = "May-Jun, Dec-Mar"; distance = 28; startPoint = "Barsu"; endPoint = "Barsu"; trekType = "Meadow/Snow"; isActive = true; isFeatured = false },
      { name = "Panwali Kantha"; slug = "panwali-kantha"; state = "Uttarakhand"; duration = 7; altitude = 4383; difficulty = "Moderate"; price = 11000; rating = 4.6; reviewCount = 89; description = "Panwali Kantha is a hidden gem in the Garhwal Himalayas, offering spectacular views of Kedar Dome, Kedarnath, Sumeru, and other peaks. The meadow of Panwali Kantha sits at 3,800m and the trek passes through the Mandakini valley, dense forests, and pristine alpine meadows. This less-crowded trail is perfect for those seeking a serene Himalayan experience away from the tourist crowds."; image = unsplash("photo-1501854140801-50d01698950b"); images = [unsplash("photo-1501854140801-50d01698950b"), unsplash("photo-1473445730015-841f29a9490b"), unsplash("photo-1545558014-8692077e9b5c")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 42; startPoint = "Ukhimath"; endPoint = "Ukhimath"; trekType = "Meadow/Alpine"; isActive = true; isFeatured = false },
      { name = "Rupin Pass"; slug = "rupin-pass"; state = "Uttarakhand"; duration = 8; altitude = 4650; difficulty = "Difficult"; price = 14000; rating = 4.9; reviewCount = 178; description = "The Rupin Pass trek is widely considered one of the most spectacular treks in India, offering an astonishing variety of landscapes — from waterfalls and river crossings to snow bridges, meadows, and a dramatic pass crossing. The trek begins in Dhaula in Uttarakhand and ends in Sangla Valley in Himachal Pradesh. The star of the show is the Rupin waterfall, a cascade that drops over 500 meters into a gorge, visible from several points on the trail."; image = unsplash("photo-1544735716-392fe2489ffa"); images = [unsplash("photo-1544735716-392fe2489ffa"), unsplash("photo-1504280390367-361c6d9f38f4"), unsplash("photo-1501854140801-50d01698950b")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 52; startPoint = "Dhaula"; endPoint = "Sangla"; trekType = "Snow/Alpine"; isActive = true; isFeatured = true },
      { name = "Bali Pass"; slug = "bali-pass"; state = "Uttarakhand"; duration = 9; altitude = 4950; difficulty = "Difficult"; price = 15500; rating = 4.7; reviewCount = 67; description = "Bali Pass is one of the challenging high-altitude treks in Uttarakhand that connects the Yamunotri region with Har Ki Dun valley. The pass sits at an elevation of 4,950m and offers breathtaking views of Bandarpunch and Swargarohini massifs. This remote trek traverses through dense forests, alpine meadows, glaciers, and moraines, making it a true wilderness adventure for experienced trekkers."; image = unsplash("photo-1504280390367-361c6d9f38f4"); images = [unsplash("photo-1504280390367-361c6d9f38f4"), unsplash("photo-1544735716-392fe2489ffa"), unsplash("photo-1501854140801-50d01698950b")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 58; startPoint = "Yamunotri"; endPoint = "Sankri"; trekType = "Snow/Glacier"; isActive = true; isFeatured = false },
      { name = "Auden's Col"; slug = "audens-col"; state = "Uttarakhand"; duration = 14; altitude = 5490; difficulty = "Extreme"; price = 28000; rating = 4.8; reviewCount = 34; description = "Auden's Col is one of the most technical and challenging high-altitude passes in the Garhwal Himalayas. Named after British geologist John Bicknell Auden who surveyed the pass in 1939, this extreme trek connects the Gangotri and Kedarnath regions via a high-altitude glacier pass at 5,490m. The trek involves technical glacier crossings, steep ascents, and navigation through complex crevasse fields, requiring prior mountaineering experience."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096640/cami1uct7alkbydbadir.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779096640/cami1uct7alkbydbadir.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096648/qcfzu06o491oxtomsoga.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096657/jjwjw7sw761m98erh8h1.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096665/nrr2za078guy1tf9547b.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096674/iqyguk8wqm1rlwuojqmj.jpg"]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 85; startPoint = "Gangotri"; endPoint = "Kedarnath"; trekType = "Glacier/Extreme"; isActive = true; isFeatured = false },
      { name = "Nanda Devi Base Camp"; slug = "nanda-devi-base-camp"; state = "Uttarakhand"; duration = 12; altitude = 4243; difficulty = "Difficult"; price = 22000; rating = 4.8; reviewCount = 112; description = "The Nanda Devi Base Camp trek is a rare journey into one of India's most protected wilderness areas — the Nanda Devi Biosphere Reserve, a UNESCO World Heritage Site. The trek follows the historic Rishi Ganga gorge to reach the base camp of Nanda Devi (7,816m), India's second highest peak. The route passes through some of the most spectacular and remote terrain in the Himalayas, with towering walls of rock and ice on all sides."; image = unsplash("photo-1579830341096-723952f0b92a"); images = [unsplash("photo-1579830341096-723952f0b92a"), unsplash("photo-1589182337358-2cb63099350c"), unsplash("photo-1486325212027-8081e485255e")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 72; startPoint = "Lata Village"; endPoint = "Lata Village"; trekType = "Forest/Alpine"; isActive = true; isFeatured = false },
      { name = "Pindari Glacier"; slug = "pindari-glacier"; state = "Uttarakhand"; duration = 6; altitude = 3820; difficulty = "Moderate"; price = 9000; rating = 4.7; reviewCount = 145; description = "The Pindari Glacier trek is one of the most accessible glacier treks in India, offering trekkers a chance to get up close with a stunning glacier without extreme difficulty. Situated in the Kumaon Himalayas, the trek passes through the beautiful Pindari Valley with dense forests, waterfalls, and charming villages. The glacier sits at the base of Nanda Kot (6,861m) and Nanda Devi East (7,434m), offering spectacular mountain views."; image = unsplash("photo-1486325212027-8081e485255e"); images = [unsplash("photo-1486325212027-8081e485255e"), unsplash("photo-1508193638397-1c4234db14d8"), unsplash("photo-1579830341096-723952f0b92a")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 45; startPoint = "Dhakuri"; endPoint = "Dhakuri"; trekType = "Glacier/Forest"; isActive = true; isFeatured = false },
      { name = "Kafni Glacier"; slug = "kafni-glacier"; state = "Uttarakhand"; duration = 8; altitude = 3660; difficulty = "Moderate"; price = 11000; rating = 4.6; reviewCount = 78; description = "The Kafni Glacier trek is a hidden gem in the Kumaon Himalayas, lesser known than its neighbor Pindari but equally beautiful. The glacier sits at the base of the formidable Nanda Kot peak and is surrounded by stunning high-altitude scenery. The trail passes through dense forests of oak, rhododendron, and birch, with the melodious Kafni River as a constant companion. The trek combines the Kafni and Pindari glaciers for a complete experience."; image = unsplash("photo-1508193638397-1c4234db14d8"); images = [unsplash("photo-1508193638397-1c4234db14d8"), unsplash("photo-1486325212027-8081e485255e"), unsplash("photo-1501854140801-50d01698950b")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 52; startPoint = "Loharkhet"; endPoint = "Loharkhet"; trekType = "Glacier/Forest"; isActive = true; isFeatured = false },
      { name = "Milam Glacier"; slug = "milam-glacier"; state = "Uttarakhand"; duration = 10; altitude = 3450; difficulty = "Moderate-Difficult"; price = 18000; rating = 4.7; reviewCount = 93; description = "Milam Glacier, once one of the most popular treks in Kumaon, is a journey through history. The trail passes through abandoned villages that were evacuated after the 1962 India-China war, offering a haunting glimpse into the region's past. The glacier sits at the base of the impressive Nanda Parbat group of peaks. The Gori Ganga river, originating from the glacier, accompanies you throughout the trek."; image = unsplash("photo-1526772662000-3f88f10405ff"); images = [unsplash("photo-1526772662000-3f88f10405ff"), unsplash("photo-1486325212027-8081e485255e"), unsplash("photo-1508193638397-1c4234db14d8")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 68; startPoint = "Munsiyari"; endPoint = "Munsiyari"; trekType = "Glacier/Remote"; isActive = true; isFeatured = false },
      { name = "Kuari Pass (Curzon Trail)"; slug = "kuari-pass"; state = "Uttarakhand"; duration = 6; altitude = 3640; difficulty = "Easy-Moderate"; price = 8000; rating = 4.8; reviewCount = 289; description = "The Kuari Pass trek, historically known as the Curzon Trail after Lord Curzon who walked it in 1905, is one of the finest ridge walks in the Garhwal Himalayas. The trail offers continuous panoramic views of peaks like Nanda Devi, Dronagiri, Kamet, and Hathi-Ghodi peaks. The walk along the Kuari ridge with the vast snowy peaks on one side and the green valleys below is an experience that stays with you forever."; image = unsplash("photo-1605540436563-5bca919ae766"); images = [unsplash("photo-1605540436563-5bca919ae766"), unsplash("photo-1501854140801-50d01698950b"), unsplash("photo-1464822759023-fed622ff2c3b")]; category = "Trek"; bestSeason = "Nov-Mar, May-Jun"; distance = 36; startPoint = "Auli"; endPoint = "Tapovan"; trekType = "Ridge/Snow"; isActive = true; isFeatured = false },
      { name = "Deoriatal Chandrashila"; slug = "deoriatal-chandrashila"; state = "Uttarakhand"; duration = 4; altitude = 4090; difficulty = "Easy"; price = 6500; rating = 4.8; reviewCount = 412; description = "The Deoriatal-Chandrashila trek is a perfect short trek that combines the serenity of Deoria Tal (a beautiful lake with reflections of the Chaukhamba peaks) with the summit experience of Chandrashila peak. The trail is ideal for beginners and families, passing through quaint Garhwali villages and dense rhododendron forests. The sunrise views from Chandrashila summit are legendary among trekkers."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779098235/sytzfdbqwe4slnrblzgl.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779098235/sytzfdbqwe4slnrblzgl.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779098245/jgcpi7n3zjxwxln0carr.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779098255/ga8ronscnuxoepezv9vg.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779098266/pzo38odcjwnn1l85jymg.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779098273/kosmewn9tqlelq65n1v8.jpg"]; category = "Trek"; bestSeason = "Mar-Jun, Sep-Nov"; distance = 18; startPoint = "Sari Village"; endPoint = "Chopta"; trekType = "Lake/Summit"; isActive = true; isFeatured = false },
      { name = "Pangarchulla Peak"; slug = "pangarchulla-peak"; state = "Uttarakhand"; duration = 6; altitude = 4586; difficulty = "Moderate-Difficult"; price = 11500; rating = 4.8; reviewCount = 134; description = "Pangarchulla is a summit trek in the Garhwal Himalayas that offers one of the most rewarding summit climbs for non-technical trekkers. The peak stands at 4,586m and commands magnificent 360-degree views of Nanda Devi, Dronagiri, Hathi-Ghodi peaks, Trishul, and the entire Kuari Pass region. The trek passes through the beautiful meadows of Khulara and Tali, making it a truly memorable experience."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110196/zicesdvggif1pxye65kq.webp"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779110196/zicesdvggif1pxye65kq.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110209/fyrqdf7p6046myyvth2z.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110218/xja7mgekq6jjbwgxobpc.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110226/rui1j6fpf44kgxhcz273.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110234/upx7hmp4yubpldnfxyzk.webp"]; category = "Trek"; bestSeason = "Nov-May"; distance = 32; startPoint = "Auli"; endPoint = "Tapovan"; trekType = "Summit/Snow"; isActive = true; isFeatured = false },
      { name = "Kedartal"; slug = "kedartal"; state = "Uttarakhand"; duration = 7; altitude = 4750; difficulty = "Difficult"; price = 13500; rating = 4.9; reviewCount = 156; description = "Kedartal is a stunning glacial lake situated at 4,750m in the Gangotri region of Uttarakhand. The lake sits at the foot of Thalay Sagar (6,904m), one of the most beautiful and technically challenging peaks in the Himalayas. The trek is short but extremely demanding, with steep ascents over moraine and rocky terrain. The view of the lake reflecting the surrounding peaks is considered among the most beautiful sights in the Indian Himalayas."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779094566/y7ly2faaw5i510f1rqml.webp"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779094566/y7ly2faaw5i510f1rqml.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779094557/mlusmmphrcf67pgjswzl.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779094548/bfy8gtldowajcx14as34.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779094534/keupqfxnevciufwajlzd.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779094526/smfl5cftr4io2eg4sqca.webp"]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 26; startPoint = "Gangotri"; endPoint = "Gangotri"; trekType = "Glacier/Lake"; isActive = true; isFeatured = true },
    ];

    let himachalTreks : [TrekTypes.TrekInput] = [
      { name = "Triund Trek"; slug = "triund-trek"; state = "Himachal Pradesh"; duration = 2; altitude = 2828; difficulty = "Easy"; price = 3500; rating = 4.7; reviewCount = 1245; description = "Triund is one of the most popular short treks near McLeod Ganj, Dharamsala. Sitting at 2,828m at the foot of the Dhauladhar range, the trek offers stunning views of the Kangra Valley below and the snow-capped peaks above. The campsite at Triund is legendary — it's one of the best places in India to experience a night under the Himalayan stars with the Dhauladhar range as your backdrop. The trail passes through beautiful forests of oak and rhododendron."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1778762878/qkhu5phox4x6diqpllii.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1778762878/qkhu5phox4x6diqpllii.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778762895/qxpcbgkqfl8tj95m7jmr.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778762930/rlmplvv2apshtxlwnbmw.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778762955/dm9qnffccv4a1mzgrejk.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1778762999/rla7vu2gzqlmfzms9n48.jpg"]; category = "Trek"; bestSeason = "Mar-Jun, Sep-Dec"; distance = 18; startPoint = "McLeod Ganj"; endPoint = "McLeod Ganj"; trekType = "Forest/Meadow"; isActive = true; isFeatured = true },
      { name = "Hampta Pass"; slug = "hampta-pass"; state = "Himachal Pradesh"; duration = 5; altitude = 4270; difficulty = "Moderate"; price = 9500; rating = 4.9; reviewCount = 678; description = "Hampta Pass is often called a 'contrast trek' because it takes you from the lush green valleys of Kullu to the barren landscape of Spiti in just a few days. Starting from Manali, the trail winds through picturesque villages, dense forests, and beautiful camping sites before crossing the dramatic 4,270m pass. On one side lies the green Kullu valley; on the other, the moon-like terrain of Lahaul and Spiti. An optional detour to Chandratal Lake makes this trek even more special."; image = unsplash("photo-1536086759-b94ed3e9e35a"); images = [unsplash("photo-1536086759-b94ed3e9e35a"), unsplash("photo-1590523741831-ab7e8b8f9c7f"), unsplash("photo-1553789269-c1ae659cef44")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 36; startPoint = "Manali"; endPoint = "Chatru"; trekType = "Snow/Alpine"; isActive = true; isFeatured = true },
      { name = "Chandratal Lake"; slug = "chandratal-lake"; state = "Himachal Pradesh"; duration = 4; altitude = 4300; difficulty = "Easy-Moderate"; price = 8000; rating = 4.9; reviewCount = 445; description = "Chandratal, meaning 'Moon Lake', is one of the most stunning high-altitude lakes in India, situated at 4,300m in the Spiti Valley. The crescent-shaped lake changes its color throughout the day — from turquoise and blue to green and grey. The trek offers spectacular views of the surrounding barren mountains and the clear high-altitude sky. The area is a UNESCO-designated wetland. The route from Batal to Chandratal is one of the most scenic drives/walks in India."; image = unsplash("photo-1590523741831-ab7e8b8f9c7f"); images = [unsplash("photo-1590523741831-ab7e8b8f9c7f"), unsplash("photo-1536086759-b94ed3e9e35a"), unsplash("photo-1506929562872-bb421503ef21")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 28; startPoint = "Batal"; endPoint = "Batal"; trekType = "Lake/Alpine"; isActive = true; isFeatured = true },
      { name = "Bhrigu Lake"; slug = "bhrigu-lake"; state = "Himachal Pradesh"; duration = 4; altitude = 4300; difficulty = "Moderate"; price = 8500; rating = 4.8; reviewCount = 312; description = "Bhrigu Lake is a sacred high-altitude lake near Manali, associated with the sage Bhrigu who is said to have meditated here. At 4,300m, the lake remains frozen for most of the year and the surrounding meadows of Rola Khuli are among the finest in Himachal Pradesh. The trail offers stunning views of Rohtang Pass, Deo Tibba, and the Kullu Valley. The lake is considered one of the highest accessible lakes in India."; image = unsplash("photo-1553789269-c1ae659cef44"); images = [unsplash("photo-1553789269-c1ae659cef44"), unsplash("photo-1590523741831-ab7e8b8f9c7f"), unsplash("photo-1536086759-b94ed3e9e35a")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 24; startPoint = "Manali"; endPoint = "Manali"; trekType = "Lake/Meadow"; isActive = true; isFeatured = false },
      { name = "Beas Kund"; slug = "beas-kund"; state = "Himachal Pradesh"; duration = 3; altitude = 3690; difficulty = "Easy"; price = 6000; rating = 4.7; reviewCount = 234; description = "Beas Kund is the glacial source of the Beas River, one of the five rivers of Punjab. The trek to Beas Kund is a perfect short trek from Manali that takes you through the beautiful Solang Valley and beyond, offering stunning views of Shitidhar, Hanuman Tibba, and Seven Sisters peaks. The turquoise-colored lake surrounded by moraines and a small glacier is a sight to behold."; image = unsplash("photo-1524673450801-b5aa9b621b76"); images = [unsplash("photo-1524673450801-b5aa9b621b76"), unsplash("photo-1553789269-c1ae659cef44"), unsplash("photo-1536086759-b94ed3e9e35a")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 20; startPoint = "Dhundi"; endPoint = "Dhundi"; trekType = "Glacier/Lake"; isActive = true; isFeatured = false },
      { name = "Pin Parvati Pass"; slug = "pin-parvati-pass"; state = "Himachal Pradesh"; duration = 11; altitude = 5319; difficulty = "Extreme"; price = 25000; rating = 4.9; reviewCount = 89; description = "Pin Parvati Pass is one of the most challenging and rewarding treks in India, connecting the lush green Parvati Valley with the barren Pin Valley in Spiti. The 5,319m pass is one of the highest in the Indian Himalayas and the trek crosses diverse landscapes — dense forests, flower-filled meadows, glaciers, moraines, and high-altitude desert. This extreme trek requires prior high-altitude experience and excellent physical fitness."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779095979/lni2oa8lfrxr05syce6o.webp"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779095979/lni2oa8lfrxr05syce6o.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779095989/nb5fd7hgu2qrjavguk2l.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096005/ybvdzafi77gcyomj884k.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096017/ahiud7htfgg5tz0p3nso.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779096034/gewqqkmgiovc3mrnq6bm.webp"]; category = "Trek"; bestSeason = "Jul-Sep"; distance = 72; startPoint = "Kheerganga"; endPoint = "Mudh Village"; trekType = "Glacier/Extreme"; isActive = true; isFeatured = true },
      { name = "Kheerganga"; slug = "kheerganga"; state = "Himachal Pradesh"; duration = 2; altitude = 2950; difficulty = "Easy"; price = 3000; rating = 4.8; reviewCount = 987; description = "Kheerganga is one of the most popular short treks in Himachal Pradesh, famous for its natural hot springs at the summit. The trek through the Parvati Valley passes through dense forests, waterfalls, and the hippie village of Chalal before reaching the beautiful meadow of Kheerganga. A dip in the natural hot springs after the trek is an experience unlike any other. The area is sacred to Lord Shiva."; image = unsplash("photo-1521336575822-6da63fb45455"); images = [unsplash("photo-1521336575822-6da63fb45455"), unsplash("photo-1553789269-c1ae659cef44"), unsplash("photo-1441974231531-c6227db76b6e")]; category = "Trek"; bestSeason = "Apr-Jun, Sep-Nov"; distance = 22; startPoint = "Barshaini"; endPoint = "Barshaini"; trekType = "Forest/Hot Springs"; isActive = true; isFeatured = false },
      { name = "Sar Pass"; slug = "sar-pass"; state = "Himachal Pradesh"; duration = 5; altitude = 4250; difficulty = "Moderate"; price = 8500; rating = 4.8; reviewCount = 456; description = "Sar Pass is one of the most beloved treks in Himachal Pradesh, offering a perfect blend of forests, meadows, and snow. Starting from Kasol in the Parvati Valley, the trek climbs through dense forests to reach the stunning Nagaru camping ground before ascending to the 4,250m pass. The descent on the other side through deep snow fields — often involving an exciting bum-slide — makes this trek particularly fun."; image = unsplash("photo-1542224566-6e85f2e6772f"); images = [unsplash("photo-1542224566-6e85f2e6772f"), unsplash("photo-1521336575822-6da63fb45455"), unsplash("photo-1441974231531-c6227db76b6e")]; category = "Trek"; bestSeason = "May-Jun"; distance = 46; startPoint = "Kasol"; endPoint = "Kasol"; trekType = "Snow/Forest"; isActive = true; isFeatured = false },
      { name = "Friendship Peak"; slug = "friendship-peak"; state = "Himachal Pradesh"; duration = 7; altitude = 5289; difficulty = "Difficult-Extreme"; price = 19500; rating = 4.8; reviewCount = 123; description = "Friendship Peak (5,289m) near Manali is one of the most accessible peaks for non-technical trekkers wanting to experience high-altitude mountaineering. The peak offers stunning 360-degree views of the entire Kullu Valley, Rohtang Pass, and dozens of surrounding peaks. The technical portion involves crampon work on steep snow slopes and basic rope work. The trek to base camp and then summit is a life-changing experience for those seeking their first Himalayan peak."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110682/cqo5betocitxbydabhvn.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779110682/cqo5betocitxbydabhvn.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110691/hgmsy6tqnqex3qje4mtb.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110702/zx4bry9uwxk4u1y4w2do.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110721/hwkwomffook87xyk7qer.webp", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779110736/zz9hhix4t8s6ux1esn9n.webp"]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 38; startPoint = "Manali"; endPoint = "Manali"; trekType = "Peak/Snow"; isActive = true; isFeatured = false },
      { name = "Deo Tibba Base Camp"; slug = "deo-tibba-base-camp"; state = "Himachal Pradesh"; duration = 8; altitude = 4060; difficulty = "Moderate"; price = 12000; rating = 4.7; reviewCount = 167; description = "The Deo Tibba Base Camp trek is one of the most rewarding moderate treks from Manali. Deo Tibba (6,001m) is a stunning peak in the Kullu district, and the trek to its base camp takes you through some of the most beautiful alpine scenery in Himachal Pradesh. The route passes through the Jagatsukh village, beautiful forests, and the stunning upper Jagatsukh valley with views of Deo Tibba, Indrasan, and Friendship Peak."; image = unsplash("photo-1553481187-be93c21490a9"); images = [unsplash("photo-1553481187-be93c21490a9"), unsplash("photo-1536086759-b94ed3e9e35a"), unsplash("photo-1486870591958-9b9d0d1dda99")]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 48; startPoint = "Jagatsukh"; endPoint = "Jagatsukh"; trekType = "Base Camp/Alpine"; isActive = true; isFeatured = false },
      { name = "Bara Bhangal"; slug = "bara-bhangal"; state = "Himachal Pradesh"; duration = 10; altitude = 3900; difficulty = "Difficult"; price = 16000; rating = 4.8; reviewCount = 45; description = "Bara Bhangal is one of the most remote and adventurous treks in India, connecting Bir in the Kangra Valley with the Ravi river valley via the high Thamsar Pass (4,708m). The isolated village of Bara Bhangal, accessible only on foot for most of the year, is the highlight of this trek. The trails pass through pristine forests, alpine meadows, and high mountain passes, offering a genuine wilderness experience away from any tourist infrastructure."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112246/ufcyc0dqordjiuahmhmi.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779112246/ufcyc0dqordjiuahmhmi.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112253/yieldkktqptv4cyifgas.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112264/mswge9qvt9ri3quvuj9k.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112274/dhegqkaso1p5pu9csdiw.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112293/kfv8uuig9ajxpyciwr8m.jpg"]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 65; startPoint = "Bir"; endPoint = "Bara Bhangal"; trekType = "Remote/Alpine"; isActive = true; isFeatured = false },
      { name = "Chandra Tal to Baralacha Pass"; slug = "chandra-tal-baralacha"; state = "Himachal Pradesh"; duration = 8; altitude = 4890; difficulty = "Difficult"; price = 16500; rating = 4.7; reviewCount = 78; description = "This high-altitude trek in Lahaul combines two iconic landmarks — the stunning Chandratal Lake and the formidable Baralacha La pass (4,890m) on the Manali-Leh highway. The trek traverses the remote Lingti and Yunam river valleys with views of the Bara Shigri glacier, the largest glacier in the Indian Himalayas. The stark beauty of the Lahaul landscape — barren peaks, blue skies, and turquoise rivers — is unlike anything else."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112672/egthybrrploazlqh5vn2.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779112672/egthybrrploazlqh5vn2.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112666/xzgkslub1puikmokrhc5.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112681/vp1fiypgu9nmt6cbw4en.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112694/usggmffyqyqzf9kpg76o.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779112706/xy3ghrefgb8vuhmlwhjg.jpg"]; category = "Trek"; bestSeason = "Jul-Sep"; distance = 55; startPoint = "Batal"; endPoint = "Sarchu"; trekType = "Desert/Alpine"; isActive = true; isFeatured = false },
      { name = "Spiti Valley Circuit"; slug = "spiti-valley-circuit"; state = "Himachal Pradesh"; duration = 12; altitude = 4550; difficulty = "Moderate"; price = 20000; rating = 4.9; reviewCount = 234; description = "The Spiti Valley Circuit is not just a trek but a complete Himalayan experience. The cold desert valley at 4,000m+ altitude is home to ancient Buddhist monasteries, dramatic landscapes, and a unique culture. The circuit covers Key Monastery, Kibber village, Pin Valley National Park, Langza, Komic, and Chandratal. This journey through the 'Middle Land' (the literal meaning of Spiti) offers an unparalleled combination of adventure, spirituality, and natural beauty."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779097189/gcfek7p9w7hzfx0qf2m.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779097189/gcfek7p9w7hzfx0qf2m.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779097196/x95zfk6bprjguerez7jr.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779097210/xz47lpwtf9gxi1n8rg9i.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779097217/xgstsxm3alodgktofgjw.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779097231/pvyk94ns57xeetcnmo5v.jpg"]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 78; startPoint = "Kaza"; endPoint = "Manali"; trekType = "Desert/Circuit"; isActive = true; isFeatured = true },
      { name = "Kinnaur Kailash Parikrama"; slug = "kinnaur-kailash"; state = "Himachal Pradesh"; duration = 5; altitude = 5015; difficulty = "Difficult"; price = 15000; rating = 4.8; reviewCount = 134; description = "Kinnaur Kailash is a sacred mountain massif in the Kinnaur district of Himachal Pradesh. The Parikrama (circumambulation) of the massif takes you through ancient tribal villages, dense pine forests, and high mountain terrain. The centerpiece is the 79-foot natural rock pillar on the peak that is considered the Shivling by Hindus and a sacred site by Buddhists. The trek offers panoramic views of the Sangla Valley and the Hindustan-Tibet Road below."; image = unsplash("photo-1518098268026-4e89f1a2cd8e"); images = [unsplash("photo-1518098268026-4e89f1a2cd8e"), unsplash("photo-1506929562872-bb421503ef21"), unsplash("photo-1519750157634-b6d493a0f77c")]; category = "Trek/Yatra"; bestSeason = "Jul-Sep"; distance = 42; startPoint = "Kalpa"; endPoint = "Kalpa"; trekType = "Pilgrimage/Alpine"; isActive = true; isFeatured = false },
      { name = "Shikari Mata"; slug = "shikari-mata"; state = "Himachal Pradesh"; duration = 2; altitude = 2850; difficulty = "Easy"; price = 4500; rating = 4.6; reviewCount = 89; description = "Shikari Mata is a beautiful short trek in the Mandi district of Himachal Pradesh. The trek leads to the ancient Shikari Mata temple at 2,850m, dedicated to the goddess of hunters. The trail passes through dense cedar and oak forests, offering stunning views of the Mandi valley and surrounding peaks. The temple itself is believed to be over 300 years old and is a significant pilgrimage site for the local community."; image = unsplash("photo-1464822759023-fed622ff2c3b"); images = [unsplash("photo-1464822759023-fed622ff2c3b"), unsplash("photo-1521336575822-6da63fb45455"), unsplash("photo-1553789269-c1ae659cef44")]; category = "Trek/Yatra"; bestSeason = "Apr-Jun, Sep-Nov"; distance = 14; startPoint = "Karsog"; endPoint = "Karsog"; trekType = "Forest/Temple"; isActive = true; isFeatured = false },
      { name = "Serolsar Lake"; slug = "serolsar-lake"; state = "Himachal Pradesh"; duration = 2; altitude = 3100; difficulty = "Easy"; price = 4000; rating = 4.7; reviewCount = 145; description = "Serolsar Lake is a serene high-altitude lake near Jalori Pass in the Kullu district. The trek through dense silver fir and oak forests leads to this picturesque lake surrounded by meadows. The Budhi Nagin temple on the lake's shore adds spiritual significance to the natural beauty. The area is also known for excellent birding opportunities. The short drive from Ani to Jalori Pass followed by the trek makes this a perfect weekend getaway."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121148/kceclvy7nrmo0eyfives.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779121148/kceclvy7nrmo0eyfives.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121136/gj7qmuvewp4opiap4bbg.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121159/x60uwpaqlcump65zjli9.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121170/czckz9keb7rx7ammn6bi.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121182/fjornppzj1fxzrpnjlj6.jpg"]; category = "Trek"; bestSeason = "Apr-Jun, Sep-Nov"; distance = 12; startPoint = "Jalori Pass"; endPoint = "Jalori Pass"; trekType = "Lake/Forest"; isActive = true; isFeatured = false },
      { name = "Thamsar Pass"; slug = "thamsar-pass"; state = "Himachal Pradesh"; duration = 7; altitude = 4708; difficulty = "Difficult"; price = 14500; rating = 4.7; reviewCount = 67; description = "Thamsar Pass (4,708m) is a challenging high-altitude pass in the Dhauladhar range that connects the Kangra Valley with the remote Bara Bhangal area. The trek is famous for its stunning ridge walk with views of the Dhauladhar range on one side and the distant Pir Panjal range on the other. The pass crossing involves steep snow slopes and the descent into the Bara Bhangal valley is through pristine wilderness."; image = unsplash("photo-1547036967-23d11aacaee0"); images = [unsplash("photo-1547036967-23d11aacaee0"), unsplash("photo-1578894381163-e72c17f2d45f"), unsplash("photo-1441974231531-c6227db76b6e")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 48; startPoint = "Bir"; endPoint = "Bara Bhangal"; trekType = "Pass/Snow"; isActive = true; isFeatured = false },
      { name = "Kalihani Pass"; slug = "kalihani-pass"; state = "Himachal Pradesh"; duration = 7; altitude = 4820; difficulty = "Difficult"; price = 15000; rating = 4.7; reviewCount = 56; description = "Kalihani Pass (4,820m) is a challenging trek in the Kullu district that connects Manali with the Parvati Valley via a high-altitude glacier pass. The trek passes through the beautiful Deo Tibba base camp area before ascending to the snow and glacier terrain of the pass. The views from the pass include Deo Tibba, Indrasan, Mukta and other stunning Kullu peaks. This is a true wilderness trek requiring prior high-altitude experience."; image = unsplash("photo-1551632436-cbf8dd35adfa"); images = [unsplash("photo-1551632436-cbf8dd35adfa"), unsplash("photo-1553481187-be93c21490a9"), unsplash("photo-1486870591958-9b9d0d1dda99")]; category = "Trek"; bestSeason = "Jun-Sep"; distance = 52; startPoint = "Manali"; endPoint = "Kasol"; trekType = "Glacier/Pass"; isActive = true; isFeatured = false },
      { name = "Kullu Eravikulam"; slug = "kullu-eravikulam"; state = "Himachal Pradesh"; duration = 5; altitude = 3600; difficulty = "Moderate"; price = 9000; rating = 4.6; reviewCount = 78; description = "This trek in the Kullu Valley takes you through the beautiful forests and meadows of the Beas river basin, crossing several glacial streams and offering continuous views of the surrounding peaks. The higher meadows of Eravikulam provide a stunning base for panoramic views of the Kullu Valley peaks. The mix of dense forests, open meadows, and mountain views makes this a well-rounded trekking experience."; image = "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121761/c41ggkfxtty4zye8evhu.jpg"; images = ["https://res.cloudinary.com/ddbcauxef/image/upload/v1779121761/c41ggkfxtty4zye8evhu.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121771/ousfqijuuxxyowijdtd2.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121782/hp1s5oghy6uiiyduaxno.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121793/uyga6cmx3h0yl4a22nts.jpg", "https://res.cloudinary.com/ddbcauxef/image/upload/v1779121803/vy5lnddf1jwehkgvc949.jpg"]; category = "Trek"; bestSeason = "May-Jun, Sep-Oct"; distance = 32; startPoint = "Manali"; endPoint = "Manali"; trekType = "Forest/Meadow"; isActive = true; isFeatured = false },
      { name = "Changer Lobang Pass"; slug = "changer-lobang-pass"; state = "Himachal Pradesh"; duration = 6; altitude = 4570; difficulty = "Difficult"; price = 13000; rating = 4.7; reviewCount = 45; description = "Changer Lobang Pass is a remote high-altitude pass in the Lahaul district of Himachal Pradesh. The trek offers a genuine off-the-beaten-path experience with minimal infrastructure and maximum wilderness. The pass connects the Chandra Valley in Lahaul with the Pattan Valley. The route passes through stunning high-altitude landscapes with views of the Kullu and Lahaul peaks. This is a trek for those seeking true solitude in the Himalayas."; image = unsplash("photo-1483728642387-6c3bdd6c93e5"); images = [unsplash("photo-1483728642387-6c3bdd6c93e5"), unsplash("photo-1519750157634-b6d493a0f77c"), unsplash("photo-1506929562872-bb421503ef21")]; category = "Trek"; bestSeason = "Jul-Sep"; distance = 40; startPoint = "Triloknath"; endPoint = "Udaipur"; trekType = "Remote/Pass"; isActive = true; isFeatured = false },
    ];

    for (t in uttarakhandTreks.values()) {
      ignore TrekLib.create(treks, trekCounter.value, t);
      trekCounter.value += 1;
    };
    for (t in himachalTreks.values()) {
      ignore TrekLib.create(treks, trekCounter.value, t);
      trekCounter.value += 1;
    };
  };

  func seedYatras() {
    let yatraData : [YatraTypes.YatraInput] = [
      { name = "Char Dham Yatra"; slug = "char-dham"; state = "Uttarakhand"; description = "The Char Dham Yatra is the most sacred pilgrimage in Hinduism, comprising four holy shrines in the Garhwal Himalayas: Yamunotri, Gangotri, Kedarnath, and Badrinath. This divine circuit is believed to cleanse all sins and grant moksha (salvation). Pilgrims undertake this journey from May to November each year. The circuit covers approximately 1,000 km and can be done by road and on foot. Each dham holds unique significance — Yamunotri is the source of the Yamuna river, Gangotri is the source of the Ganga, Kedarnath houses one of the 12 Jyotirlingas, and Badrinath is the abode of Lord Vishnu."; significance = "Considered the holiest pilgrimage in Hinduism, completing Char Dham is believed to grant salvation and freedom from the cycle of birth and death"; bestTime = "May to June and September to October"; howToReach = "By road from Haridwar/Rishikesh, helicopter services available for Kedarnath"; accommodation = "Dharamshalas, GMVN guesthouses, private hotels at all four dhams"; price = 25000; image = unsplash("photo-1545558014-8692077e9b5c"); images = [unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1609766418204-94aaeaf0f4b7"), unsplash("photo-1473445730015-841f29a9490b"), unsplash("photo-1519681393784-d120267933ba")]; isActive = true },
      { name = "Panch Kedar"; slug = "panch-kedar"; state = "Uttarakhand"; description = "Panch Kedar refers to the five sacred Hindu temples dedicated to Lord Shiva in the Garhwal Himalayas: Kedarnath, Tungnath, Rudranath, Madhyamaheshwar, and Kalpeshwar. According to Hindu mythology, the Pandavas sought to atone for the sins of fratricide after the Kurukshetra war by seeking Lord Shiva. Shiva eluded them in the form of a bull, and his body parts appeared at five different locations, which became the five sacred shrines. The complete Panch Kedar pilgrimage is one of the most physically demanding and spiritually rewarding journeys in India."; significance = "The five manifestations of Lord Shiva in the Garhwal Himalayas, completing all five is considered equivalent to the highest spiritual attainment"; bestTime = "May to June and September to November"; howToReach = "By road from Rishikesh to respective base camps, then on foot"; accommodation = "Forest rest houses, dharamshalas, and camping at most locations"; price = 35000; image = unsplash("photo-1473445730015-841f29a9490b"); images = [unsplash("photo-1473445730015-841f29a9490b"), unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1609766418204-94aaeaf0f4b7")]; isActive = true },
      { name = "Panch Badri"; slug = "panch-badri"; state = "Uttarakhand"; description = "Panch Badri comprises five sacred Vishnu temples in the Chamoli district of Uttarakhand: Badrinath (the main shrine), Yogdhyan Badri at Pandukeshwar, Bhavishya Badri at Subain, Vridha Badri at Animath, and Adi Badri near Karnaprayag. Together, these five temples form a complete pilgrimage circuit associated with Lord Vishnu in the Himalayan region. Badrinath, the main temple, is one of the four Char Dham sites and one of the 108 Divya Desam."; significance = "Five sacred manifestations of Lord Vishnu in the Himalayas, representing different aspects of the divine"; bestTime = "May to June and September to October"; howToReach = "By road from Haridwar/Rishikesh to Badrinath, other temples accessible by road and short walks"; accommodation = "Hotels, dharamshalas, and GMVN guesthouses at all locations"; price = 18000; image = unsplash("photo-1609766418204-94aaeaf0f4b7"); images = [unsplash("photo-1609766418204-94aaeaf0f4b7"), unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1473445730015-841f29a9490b")]; isActive = true },
      { name = "Hemkund Sahib Yatra"; slug = "hemkund-sahib"; state = "Uttarakhand"; description = "Hemkund Sahib is one of the most revered Sikh pilgrimage sites in the world, situated at an altitude of 4,329m in the Chamoli district of Uttarakhand. The gurdwara sits on the banks of a glacial lake surrounded by seven mountain peaks, creating one of the most spectacular settings of any religious site in the world. According to Sikh scripture (Dasam Granth), Guru Gobind Singh meditated here in a previous life. The pilgrimage season runs from June to September."; significance = "One of the highest Gurudwaras in the world, sacred to Sikhs as the meditation site of Guru Gobind Singh in a previous life"; bestTime = "June to September"; howToReach = "By road from Rishikesh to Govindghat, then trek 19 km to Hemkund"; accommodation = "Langar (free community kitchen) at the Gurudwara, hotels in Ghangaria"; price = 8500; image = unsplash("photo-1519681393784-d120267933ba"); images = [unsplash("photo-1519681393784-d120267933ba"), unsplash("photo-1506905925346-21bda4d32df4"), unsplash("photo-1473445730015-841f29a9490b")]; isActive = true },
      { name = "Adi Kailash & Om Parvat Yatra"; slug = "adi-kailash"; state = "Uttarakhand"; description = "Adi Kailash (5,945m), also known as Chota Kailash or Baba Kailash, is considered the Indian equivalent of Mount Kailash in Tibet. Located in the Pithoragarh district near the India-Nepal-Tibet trijunction, the yatra also includes Om Parvat — a peak where a natural snow formation in the shape of 'Om' appears every year. The journey passes through high-altitude deserts, ancient trading villages, and dramatic landscapes similar to Tibet. Kuber Kund and the Parvati Sarovar are other sacred sites on this route."; significance = "Sacred to both Hindus and Buddhists, considered equivalent to the holy Mt. Kailash in Tibet for those who cannot visit Tibet"; bestTime = "May to June and September to October"; howToReach = "By road from Pithoragarh to Dharchula, then by jeep and trek"; accommodation = "Forest rest houses, guesthouses in Dharchula and Gunji"; price = 22000; image = unsplash("photo-1501854140801-50d01698950b"); images = [unsplash("photo-1501854140801-50d01698950b"), unsplash("photo-1526772662000-3f88f10405ff"), unsplash("photo-1486325212027-8081e485255e")]; isActive = true },
      { name = "Kartik Swami Temple"; slug = "kartik-swami"; state = "Uttarakhand"; description = "Kartik Swami temple, dedicated to Kartikeya (the elder son of Lord Shiva), is perched on a rocky hilltop at 3,050m in the Rudraprayag district. The temple offers breathtaking panoramic views of the Himalayan peaks including Kedarnath, Chaukhamba, Neelkanth, Nanda Devi, and Trishul. The 3 km trek through lush forests to the temple is a spiritually uplifting experience. The temple is believed to be over 700 years old and is the only major temple dedicated to Kartikeya in North India."; significance = "Dedicated to Kartikeya, son of Lord Shiva, one of the most important temples to this deity in North India"; bestTime = "Year-round, best in April-June and September-November"; howToReach = "By road from Rishikesh to Pokhari village, then 3 km trek"; accommodation = "Guesthouses in Pokhari and nearby villages"; price = 5500; image = unsplash("photo-1464278533981-50106e6176b1"); images = [unsplash("photo-1464278533981-50106e6176b1"), unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1473445730015-841f29a9490b")]; isActive = true },
      { name = "Triyuginarayan Temple"; slug = "triyuginarayan"; state = "Uttarakhand"; description = "Triyuginarayan temple in Rudraprayag district is the legendary site of the divine marriage of Lord Shiva and Goddess Parvati. According to Hindu mythology, Lord Vishnu gave Parvati in marriage to Shiva here, and the eternal flame (Akhand Dhuni) has been burning in front of the temple since that time — through three yugas (eras), which is how the temple got its name. The ashes from this eternal flame are believed to be sacred. The temple is 12 km from Kedarnath."; significance = "Sacred wedding site of Lord Shiva and Goddess Parvati with an eternal flame burning since the time of their divine wedding"; bestTime = "May to June and September to October"; howToReach = "By road from Rishikesh via Guptkashi, accessible year-round by road"; accommodation = "GMVN guesthouse, dharamshalas, and private guesthouses"; price = 6000; image = unsplash("photo-1556296240-b6b6e89c0f9f"); images = [unsplash("photo-1556296240-b6b6e89c0f9f"), unsplash("photo-1545558014-8692077e9b5c"), unsplash("photo-1609766418204-94aaeaf0f4b7")]; isActive = true },
      { name = "Mani Mahesh Yatra"; slug = "mani-mahesh"; state = "Himachal Pradesh"; description = "Mani Mahesh Yatra is one of the most sacred and challenging pilgrimages in Himachal Pradesh, leading to the holy Mani Mahesh Lake (4,350m) at the foot of the sacred Mani Mahesh Kailash peak (5,653m). The lake is believed to be the abode of Lord Shiva, and the Mani Mahesh Kailash peak is considered his throne. The pilgrimage is done during the Janmashtami festival period (August-September). The trek from Hadsar covers 14 km of challenging mountain terrain."; significance = "Sacred abode of Lord Shiva in the Chamba district, the lake and peak are considered equivalent to Mt. Kailash for the people of Himachal Pradesh"; bestTime = "August to September (Janmashtami period)"; howToReach = "By road from Chamba to Hadsar, then 14 km trek to the lake"; accommodation = "Tents, dharamshalas, and basic guesthouses along the route"; price = 9500; image = unsplash("photo-1553789269-c1ae659cef44"); images = [unsplash("photo-1553789269-c1ae659cef44"), unsplash("photo-1518098268026-4e89f1a2cd8e"), unsplash("photo-1521336575822-6da63fb45455")]; isActive = true },
      { name = "Kinnaur Kailash Parikrama"; slug = "kinnaur-kailash-parikrama"; state = "Himachal Pradesh"; description = "The Kinnaur Kailash Parikrama is a circumambulation of the sacred Kinnaur Kailash mountain (6,050m) in the Kinnaur district of Himachal Pradesh. The parikrama covers approximately 80 km over 5 days and takes you through ancient Kinnauri villages, dense forests, and high mountain terrain. The centerpiece is a 79-foot natural rock pillar at 4,800m that changes color throughout the day and is worshipped by both Hindus and Buddhists. The pilgrimage is done during the Dussehra period."; significance = "Sacred to both Hindus and Buddhists of the Kinnaur district, the natural rock pillar (Shivling) is worshipped as a divine manifestation"; bestTime = "August to October"; howToReach = "By road from Shimla to Kalpa (220 km), then trek"; accommodation = "Guesthouses in Kalpa, PWD rest houses, and camping along the route"; price = 15000; image = unsplash("photo-1518098268026-4e89f1a2cd8e"); images = [unsplash("photo-1518098268026-4e89f1a2cd8e"), unsplash("photo-1506929562872-bb421503ef21"), unsplash("photo-1519750157634-b6d493a0f77c")]; isActive = true },
      { name = "Shrikhand Mahadev Yatra"; slug = "shrikhand-mahadev"; state = "Himachal Pradesh"; description = "Shrikhand Mahadev is one of the most challenging and sacred pilgrimages in Himachal Pradesh, leading to a 72-foot natural Shivling at 5,227m in the Kullu district. The yatra involves a grueling 35 km trek each way through dense forests, meadows, snowfields, and rocky terrain. The trail passes through several sacred spots including Parvati Bagh, Bheem Dwari, and Kalinaag. The pilgrimage is done during the Shravan month (July-August) and thousands of devotees brave the difficult terrain every year."; significance = "One of the most demanding and revered pilgrimages in Himachal Pradesh, dedicated to a towering natural Shivling at high altitude"; bestTime = "July to August"; howToReach = "By road from Shimla to Nirmand, then trek from Bagi base camp"; accommodation = "Dharamshalas and tents at Bashleo Pass and Bheem Dwari"; price = 12000; image = unsplash("photo-1521336575822-6da63fb45455"); images = [unsplash("photo-1521336575822-6da63fb45455"), unsplash("photo-1518098268026-4e89f1a2cd8e"), unsplash("photo-1553789269-c1ae659cef44")]; isActive = true },
      { name = "Churdhar Yatra"; slug = "churdhar"; state = "Himachal Pradesh"; description = "Churdhar (3,647m) is the highest peak in the outer Himalayas of Himachal Pradesh and is home to the Chureshwar Mahadev temple, dedicated to Lord Shiva. The peak is located in the Sirmour district and the trek passes through dense forests of cedar, oak, and rhododendron before emerging above the tree line. The summit offers spectacular 360-degree views of the Himalayan peaks and the plains of Punjab and Haryana below. The forest around Churdhar is home to diverse wildlife including Himalayan black bear."; significance = "Highest peak in the outer Himalayas with an ancient Shiva temple, the summit view encompasses both the snowy Himalayas and the plains below"; bestTime = "April to June and September to November"; howToReach = "By road from Nahan to Nohra, then 14 km trek to summit"; accommodation = "Forest rest house at base, temple dharamshala near summit"; price = 7500; image = unsplash("photo-1486325212027-8081e485255e"); images = [unsplash("photo-1486325212027-8081e485255e"), unsplash("photo-1521336575822-6da63fb45455"), unsplash("photo-1518098268026-4e89f1a2cd8e")]; isActive = true },
    ];

    for (y in yatraData.values()) {
      ignore YatraLib.create(yatras, yatraCounter.value, y);
      yatraCounter.value += 1;
    };
  };

  func seedTrailConditions() {
    let now = Time.now();
    let validUntil = now + 1_209_600_000_000_000; // 14 days in nanoseconds
    let seeds : [TrailTypes.TrailCondition] = [
      { trekSlug = "kedarkantha-trek"; condition = #good; notes = "Trail clear, light snow on summit section. Crampons recommended above 3500m."; updatedAt = now; validUntil = validUntil },
      { trekSlug = "triund-trek"; condition = #moderate; notes = "Some loose stones on upper section after recent rainfall. Manageable with trekking poles."; updatedAt = now; validUntil = validUntil },
      { trekSlug = "hampta-pass"; condition = #good; notes = "Pass is open. Snow bridge at Jwara campsite is stable. No issues reported."; updatedAt = now; validUntil = validUntil },
      { trekSlug = "roopkund-trek"; condition = #difficult; notes = "Heavy snow above Ali Bugyal. Fixed ropes placed on Juragali section. Experienced guides required."; updatedAt = now; validUntil = validUntil },
      { trekSlug = "valley-of-flowers"; condition = #good; notes = "Peak bloom season. Trail is well maintained. Bridge over Pushpawati river in good condition."; updatedAt = now; validUntil = validUntil },
    ];
    for (tc in seeds.values()) {
      ignore TrailLib.setTrailCondition(trailConditions, tc);
    };
  };

  if (not seedDone) {
    seedTreks();
    seedYatras();
    BatchLib.seedBatches(batches, batchCounter, 40);
    seedTrailConditions();
    seedDone := true;
    stableSeedDone := true;
  };

  // Include domain API mixins
  include TrekApi(treks, trekCounter, admins);
  include YatraApi(yatras, yatraCounter, admins);
  include BookingApi(bookings, bookingCounter, admins);
  include QueryApi(queries, queryCounter, admins);
  include UserApi(profiles);
  include BlogApi(blogs, blogCounter, admins);
  include PromoApi(promos, admins);
  include BatchApi(batches, batchCounter);
  include UgcApi(ugcPhotos, ugcCounter);
  include TrailApi(trailConditions);
  include AdminApi(admins);

  public query func getStats() : async { totalTreks : Nat; totalBookings : Nat; totalQueries : Nat; totalUsers : Nat } {
    {
      totalTreks = treks.size();
      totalBookings = bookings.size();
      totalQueries = queries.size();
      totalUsers = profiles.size();
    }
  };

  public query func getWeatherCache(location : Text) : async ?Common.WeatherCache {
    weatherCache.get(location)
  };

  public func setWeatherCache(location : Text, data : Text) : async () {
    let now = Time.now().toNat();
    let entry : Common.WeatherCache = {
      location = location;
      data = data;
      fetchedAt = now;
      ttl = 3600;
    };
    weatherCache.add(location, entry)
  };
};
