/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'joinedAt' : IDL.Int,
  'medicalConditions' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const Result_10 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const UgcPhoto = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'photoData' : IDL.Text,
  'trekDate' : IDL.Text,
  'trekSlug' : IDL.Text,
  'trekkerName' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const Result_4 = IDL.Variant({ 'ok' : UgcPhoto, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const TrekBatchPublic = IDL.Record({
  'id' : IDL.Nat,
  'trekId' : IDL.Nat,
  'priceOverride' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
  'totalSlots' : IDL.Nat,
  'availableSlots' : IDL.Nat,
  'batchDate' : Timestamp,
});
export const Result_3 = IDL.Variant({
  'ok' : TrekBatchPublic,
  'err' : IDL.Text,
});
export const BlogInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'heroImage' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const BookingInput = IDL.Record({
  'itemId' : IDL.Nat,
  'email' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'travelerName' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'itemName' : IDL.Text,
  'itemType' : IDL.Text,
  'phone' : IDL.Text,
  'groupSize' : IDL.Nat,
  'batchDate' : Timestamp,
});
export const PromoInput = IDL.Record({
  'expiresAt' : Timestamp,
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'maxUses' : IDL.Nat,
});
export const TrekInput = IDL.Record({
  'duration' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'altitude' : IDL.Nat,
  'description' : IDL.Text,
  'distance' : IDL.Nat,
  'isActive' : IDL.Bool,
  'state' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'trekType' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'image' : IDL.Text,
  'endPoint' : IDL.Text,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'startPoint' : IDL.Text,
  'bestSeason' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'paymentTimestamp' : IDL.Opt(IDL.Nat),
  'itemId' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'razorpaySignature' : IDL.Opt(IDL.Text),
  'advanceAmount' : IDL.Nat,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'travelerName' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'itemName' : IDL.Text,
  'itemType' : IDL.Text,
  'phone' : IDL.Text,
  'bookingRef' : IDL.Text,
  'groupSize' : IDL.Nat,
  'batchDate' : Timestamp,
  'paymentProvider' : IDL.Text,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(Booking),
  'err' : IDL.Text,
});
export const LeadQuery = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'preferredDates' : IDL.Text,
  'message' : IDL.Text,
  'preferredTrek' : IDL.Text,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
  'groupSize' : IDL.Nat,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(LeadQuery),
  'err' : IDL.Text,
});
export const TrailCondition = IDL.Record({
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'trekSlug' : IDL.Text,
  'validUntil' : IDL.Int,
  'condition' : IDL.Variant({
    'closed' : IDL.Null,
    'good' : IDL.Null,
    'moderate' : IDL.Null,
    'difficult' : IDL.Null,
  }),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'heroImage' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Trek = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'altitude' : IDL.Nat,
  'description' : IDL.Text,
  'distance' : IDL.Nat,
  'isActive' : IDL.Bool,
  'state' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'trekType' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'image' : IDL.Text,
  'endPoint' : IDL.Text,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'startPoint' : IDL.Text,
  'bestSeason' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const WeatherCache = IDL.Record({
  'ttl' : IDL.Nat,
  'fetchedAt' : IDL.Nat,
  'data' : IDL.Text,
  'location' : IDL.Text,
});
export const Yatra = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'accommodation' : IDL.Text,
  'isActive' : IDL.Bool,
  'state' : IDL.Text,
  'significance' : IDL.Text,
  'howToReach' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ProfileInput = IDL.Record({
  'name' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_5 = IDL.Variant({
  'ok' : TrailCondition,
  'err' : IDL.Text,
});
export const QueryInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDates' : IDL.Text,
  'message' : IDL.Text,
  'preferredTrek' : IDL.Text,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
  'groupSize' : IDL.Nat,
});
export const UgcPhotoInput = IDL.Record({
  'photoData' : IDL.Text,
  'trekDate' : IDL.Text,
  'trekSlug' : IDL.Text,
  'trekkerName' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [Result_10], []),
  'approveUgcPhoto' : IDL.Func([IDL.Text], [Result_4], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [Result_2], []),
  'createBatch' : IDL.Func(
      [IDL.Nat, Timestamp, IDL.Nat, IDL.Opt(IDL.Nat)],
      [Result_3],
      [],
    ),
  'createBlog' : IDL.Func([BlogInput], [Result_1], []),
  'createBooking' : IDL.Func([BookingInput], [Result_1], []),
  'createPromoCode' : IDL.Func([PromoInput], [Result_2], []),
  'createTrek' : IDL.Func([TrekInput], [Result_1], []),
  'deleteBatch' : IDL.Func([IDL.Nat], [Result_6], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [Result_2], []),
  'deleteTrek' : IDL.Func([IDL.Nat], [Result_2], []),
  'getAllBatches' : IDL.Func([], [IDL.Vec(TrekBatchPublic)], ['query']),
  'getAllBookings' : IDL.Func([], [Result_9], []),
  'getAllQueries' : IDL.Func([], [Result_8], []),
  'getAllTrailConditions' : IDL.Func([], [IDL.Vec(TrailCondition)], ['query']),
  'getBatchById' : IDL.Func([IDL.Nat], [IDL.Opt(TrekBatchPublic)], ['query']),
  'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getFeaturedTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getPendingUgcPhotos' : IDL.Func([], [IDL.Vec(UgcPhoto)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTreks' : IDL.Nat,
          'totalQueries' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTrailCondition' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrailCondition)],
      ['query'],
    ),
  'getTrekBatches' : IDL.Func([IDL.Nat], [IDL.Vec(TrekBatchPublic)], ['query']),
  'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'getUgcPhotosByTrek' : IDL.Func([IDL.Text], [IDL.Vec(UgcPhoto)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserByReferralCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherCache' : IDL.Func([IDL.Text], [IDL.Opt(WeatherCache)], ['query']),
  'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
  'getYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
  'initPayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [Result_7], []),
  'processReferral' : IDL.Func([IDL.Text], [Result_6], []),
  'rejectUgcPhoto' : IDL.Func([IDL.Text], [Result_4], []),
  'saveProfile' : IDL.Func([ProfileInput], [Result_2], []),
  'setTrailCondition' : IDL.Func([TrailCondition], [Result_5], []),
  'setWeatherCache' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitQuery' : IDL.Func([QueryInput], [Result_1], []),
  'submitUgcPhoto' : IDL.Func([UgcPhotoInput], [Result_4], []),
  'updateBatch' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
      [Result_3],
      [],
    ),
  'updateBlog' : IDL.Func([IDL.Nat, BlogInput], [Result_2], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
  'updateQueryStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
  'updateTrek' : IDL.Func([IDL.Nat, TrekInput], [Result_2], []),
  'validatePromoCode' : IDL.Func([IDL.Text], [Result_1], ['query']),
  'verifyPayment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'joinedAt' : IDL.Int,
    'medicalConditions' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const Result_10 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const UgcPhoto = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'photoData' : IDL.Text,
    'trekDate' : IDL.Text,
    'trekSlug' : IDL.Text,
    'trekkerName' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const Result_4 = IDL.Variant({ 'ok' : UgcPhoto, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const TrekBatchPublic = IDL.Record({
    'id' : IDL.Nat,
    'trekId' : IDL.Nat,
    'priceOverride' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
    'totalSlots' : IDL.Nat,
    'availableSlots' : IDL.Nat,
    'batchDate' : Timestamp,
  });
  const Result_3 = IDL.Variant({ 'ok' : TrekBatchPublic, 'err' : IDL.Text });
  const BlogInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'heroImage' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const BookingInput = IDL.Record({
    'itemId' : IDL.Nat,
    'email' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'travelerName' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'itemName' : IDL.Text,
    'itemType' : IDL.Text,
    'phone' : IDL.Text,
    'groupSize' : IDL.Nat,
    'batchDate' : Timestamp,
  });
  const PromoInput = IDL.Record({
    'expiresAt' : Timestamp,
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'maxUses' : IDL.Nat,
  });
  const TrekInput = IDL.Record({
    'duration' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'altitude' : IDL.Nat,
    'description' : IDL.Text,
    'distance' : IDL.Nat,
    'isActive' : IDL.Bool,
    'state' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'trekType' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'image' : IDL.Text,
    'endPoint' : IDL.Text,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'startPoint' : IDL.Text,
    'bestSeason' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'paymentTimestamp' : IDL.Opt(IDL.Nat),
    'itemId' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'razorpaySignature' : IDL.Opt(IDL.Text),
    'advanceAmount' : IDL.Nat,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'travelerName' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'itemName' : IDL.Text,
    'itemType' : IDL.Text,
    'phone' : IDL.Text,
    'bookingRef' : IDL.Text,
    'groupSize' : IDL.Nat,
    'batchDate' : Timestamp,
    'paymentProvider' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Vec(Booking), 'err' : IDL.Text });
  const LeadQuery = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'preferredDates' : IDL.Text,
    'message' : IDL.Text,
    'preferredTrek' : IDL.Text,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
    'groupSize' : IDL.Nat,
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(LeadQuery), 'err' : IDL.Text });
  const TrailCondition = IDL.Record({
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'trekSlug' : IDL.Text,
    'validUntil' : IDL.Int,
    'condition' : IDL.Variant({
      'closed' : IDL.Null,
      'good' : IDL.Null,
      'moderate' : IDL.Null,
      'difficult' : IDL.Null,
    }),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'heroImage' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Trek = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'altitude' : IDL.Nat,
    'description' : IDL.Text,
    'distance' : IDL.Nat,
    'isActive' : IDL.Bool,
    'state' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'trekType' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'image' : IDL.Text,
    'endPoint' : IDL.Text,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'startPoint' : IDL.Text,
    'bestSeason' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const WeatherCache = IDL.Record({
    'ttl' : IDL.Nat,
    'fetchedAt' : IDL.Nat,
    'data' : IDL.Text,
    'location' : IDL.Text,
  });
  const Yatra = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'accommodation' : IDL.Text,
    'isActive' : IDL.Bool,
    'state' : IDL.Text,
    'significance' : IDL.Text,
    'howToReach' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ProfileInput = IDL.Record({
    'name' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : TrailCondition, 'err' : IDL.Text });
  const QueryInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDates' : IDL.Text,
    'message' : IDL.Text,
    'preferredTrek' : IDL.Text,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
    'groupSize' : IDL.Nat,
  });
  const UgcPhotoInput = IDL.Record({
    'photoData' : IDL.Text,
    'trekDate' : IDL.Text,
    'trekSlug' : IDL.Text,
    'trekkerName' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  
  return IDL.Service({
    'addWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [Result_10], []),
    'approveUgcPhoto' : IDL.Func([IDL.Text], [Result_4], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [Result_2], []),
    'createBatch' : IDL.Func(
        [IDL.Nat, Timestamp, IDL.Nat, IDL.Opt(IDL.Nat)],
        [Result_3],
        [],
      ),
    'createBlog' : IDL.Func([BlogInput], [Result_1], []),
    'createBooking' : IDL.Func([BookingInput], [Result_1], []),
    'createPromoCode' : IDL.Func([PromoInput], [Result_2], []),
    'createTrek' : IDL.Func([TrekInput], [Result_1], []),
    'deleteBatch' : IDL.Func([IDL.Nat], [Result_6], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [Result_2], []),
    'deleteTrek' : IDL.Func([IDL.Nat], [Result_2], []),
    'getAllBatches' : IDL.Func([], [IDL.Vec(TrekBatchPublic)], ['query']),
    'getAllBookings' : IDL.Func([], [Result_9], []),
    'getAllQueries' : IDL.Func([], [Result_8], []),
    'getAllTrailConditions' : IDL.Func(
        [],
        [IDL.Vec(TrailCondition)],
        ['query'],
      ),
    'getBatchById' : IDL.Func([IDL.Nat], [IDL.Opt(TrekBatchPublic)], ['query']),
    'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getFeaturedTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getPendingUgcPhotos' : IDL.Func([], [IDL.Vec(UgcPhoto)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTreks' : IDL.Nat,
            'totalQueries' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTrailCondition' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrailCondition)],
        ['query'],
      ),
    'getTrekBatches' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TrekBatchPublic)],
        ['query'],
      ),
    'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'getUgcPhotosByTrek' : IDL.Func([IDL.Text], [IDL.Vec(UgcPhoto)], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserByReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherCache' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WeatherCache)],
        ['query'],
      ),
    'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
    'getYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
    'initPayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [Result_7], []),
    'processReferral' : IDL.Func([IDL.Text], [Result_6], []),
    'rejectUgcPhoto' : IDL.Func([IDL.Text], [Result_4], []),
    'saveProfile' : IDL.Func([ProfileInput], [Result_2], []),
    'setTrailCondition' : IDL.Func([TrailCondition], [Result_5], []),
    'setWeatherCache' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitQuery' : IDL.Func([QueryInput], [Result_1], []),
    'submitUgcPhoto' : IDL.Func([UgcPhotoInput], [Result_4], []),
    'updateBatch' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
        [Result_3],
        [],
      ),
    'updateBlog' : IDL.Func([IDL.Nat, BlogInput], [Result_2], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
    'updateQueryStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
    'updateTrek' : IDL.Func([IDL.Nat, TrekInput], [Result_2], []),
    'validatePromoCode' : IDL.Func([IDL.Text], [Result_1], ['query']),
    'verifyPayment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };