/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : bigint,
  'heroImage' : string,
  'excerpt' : string,
  'category' : string,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : Timestamp,
  'author' : string,
  'readTime' : bigint,
  'heroImage' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Booking {
  'id' : bigint,
  'razorpayPaymentId' : [] | [string],
  'status' : string,
  'paymentTimestamp' : [] | [bigint],
  'itemId' : bigint,
  'paymentStatus' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'email' : string,
  'razorpaySignature' : [] | [string],
  'advanceAmount' : bigint,
  'razorpayOrderId' : [] | [string],
  'travelerName' : string,
  'totalAmount' : bigint,
  'itemName' : string,
  'itemType' : string,
  'phone' : string,
  'bookingRef' : string,
  'groupSize' : bigint,
  'batchDate' : Timestamp,
  'paymentProvider' : string,
}
export interface BookingInput {
  'itemId' : bigint,
  'email' : string,
  'advanceAmount' : bigint,
  'travelerName' : string,
  'totalAmount' : bigint,
  'itemName' : string,
  'itemType' : string,
  'phone' : string,
  'groupSize' : bigint,
  'batchDate' : Timestamp,
}
export interface LeadQuery {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'preferredDates' : string,
  'message' : string,
  'preferredTrek' : string,
  'phone' : string,
  'budget' : string,
  'groupSize' : bigint,
}
export interface ProfileInput {
  'name' : string,
  'medicalConditions' : string,
  'email' : string,
  'experience' : string,
  'bloodGroup' : string,
  'phone' : string,
}
export interface PromoInput {
  'expiresAt' : Timestamp,
  'code' : string,
  'discountPercent' : bigint,
  'maxUses' : bigint,
}
export interface QueryInput {
  'name' : string,
  'email' : string,
  'preferredDates' : string,
  'message' : string,
  'preferredTrek' : string,
  'phone' : string,
  'budget' : string,
  'groupSize' : bigint,
}
export type Result = { 'ok' : Booking } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_10 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_2 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_3 = { 'ok' : TrekBatchPublic } |
  { 'err' : string };
export type Result_4 = { 'ok' : UgcPhoto } |
  { 'err' : string };
export type Result_5 = { 'ok' : TrailCondition } |
  { 'err' : string };
export type Result_6 = { 'ok' : null } |
  { 'err' : string };
export type Result_7 = { 'ok' : string } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<LeadQuery> } |
  { 'err' : string };
export type Result_9 = { 'ok' : Array<Booking> } |
  { 'err' : string };
export type Timestamp = bigint;
export interface TrailCondition {
  'updatedAt' : bigint,
  'notes' : string,
  'trekSlug' : string,
  'validUntil' : bigint,
  'condition' : { 'closed' : null } |
    { 'good' : null } |
    { 'moderate' : null } |
    { 'difficult' : null },
}
export interface Trek {
  'id' : bigint,
  'duration' : bigint,
  'difficulty' : string,
  'name' : string,
  'slug' : string,
  'altitude' : bigint,
  'description' : string,
  'distance' : bigint,
  'isActive' : boolean,
  'state' : string,
  'isFeatured' : boolean,
  'trekType' : string,
  'category' : string,
  'rating' : number,
  'image' : string,
  'endPoint' : string,
  'price' : bigint,
  'reviewCount' : bigint,
  'startPoint' : string,
  'bestSeason' : string,
  'images' : Array<string>,
}
export interface TrekBatchPublic {
  'id' : bigint,
  'trekId' : bigint,
  'priceOverride' : [] | [bigint],
  'isActive' : boolean,
  'totalSlots' : bigint,
  'availableSlots' : bigint,
  'batchDate' : Timestamp,
}
export interface TrekInput {
  'duration' : bigint,
  'difficulty' : string,
  'name' : string,
  'slug' : string,
  'altitude' : bigint,
  'description' : string,
  'distance' : bigint,
  'isActive' : boolean,
  'state' : string,
  'isFeatured' : boolean,
  'trekType' : string,
  'category' : string,
  'rating' : number,
  'image' : string,
  'endPoint' : string,
  'price' : bigint,
  'reviewCount' : bigint,
  'startPoint' : string,
  'bestSeason' : string,
  'images' : Array<string>,
}
export interface UgcPhoto {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'photoData' : string,
  'trekDate' : string,
  'trekSlug' : string,
  'trekkerName' : string,
  'uploadedAt' : bigint,
}
export interface UgcPhotoInput {
  'photoData' : string,
  'trekDate' : string,
  'trekSlug' : string,
  'trekkerName' : string,
}
export interface UserProfile {
  'principal' : Principal,
  'referralCode' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'joinedAt' : bigint,
  'medicalConditions' : string,
  'email' : string,
  'experience' : string,
  'referredBy' : [] | [string],
  'bloodGroup' : string,
  'phone' : string,
  'walletBalance' : bigint,
}
export interface WeatherCache {
  'ttl' : bigint,
  'fetchedAt' : bigint,
  'data' : string,
  'location' : string,
}
export interface Yatra {
  'id' : bigint,
  'name' : string,
  'bestTime' : string,
  'slug' : string,
  'description' : string,
  'accommodation' : string,
  'isActive' : boolean,
  'state' : string,
  'significance' : string,
  'howToReach' : string,
  'image' : string,
  'price' : bigint,
  'images' : Array<string>,
}
export interface _SERVICE {
  'addWalletBalance' : ActorMethod<[Principal, bigint], Result_10>,
  'approveUgcPhoto' : ActorMethod<[string], Result_4>,
  'cancelBooking' : ActorMethod<[bigint], Result_2>,
  'createBatch' : ActorMethod<
    [bigint, Timestamp, bigint, [] | [bigint]],
    Result_3
  >,
  'createBlog' : ActorMethod<[BlogInput], Result_1>,
  'createBooking' : ActorMethod<[BookingInput], Result_1>,
  'createPromoCode' : ActorMethod<[PromoInput], Result_2>,
  'createTrek' : ActorMethod<[TrekInput], Result_1>,
  'deleteBatch' : ActorMethod<[bigint], Result_6>,
  'deleteBlog' : ActorMethod<[bigint], Result_2>,
  'deleteTrek' : ActorMethod<[bigint], Result_2>,
  'getAllBatches' : ActorMethod<[], Array<TrekBatchPublic>>,
  'getAllBookings' : ActorMethod<[], Result_9>,
  'getAllQueries' : ActorMethod<[], Result_8>,
  'getAllTrailConditions' : ActorMethod<[], Array<TrailCondition>>,
  'getBatchById' : ActorMethod<[bigint], [] | [TrekBatchPublic]>,
  'getBlogBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogs' : ActorMethod<[], Array<BlogPost>>,
  'getFeaturedTreks' : ActorMethod<[], Array<Trek>>,
  'getPendingUgcPhotos' : ActorMethod<[], Array<UgcPhoto>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStats' : ActorMethod<
    [],
    {
      'totalTreks' : bigint,
      'totalQueries' : bigint,
      'totalBookings' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getTrailCondition' : ActorMethod<[string], [] | [TrailCondition]>,
  'getTrekBatches' : ActorMethod<[bigint], Array<TrekBatchPublic>>,
  'getTrekBySlug' : ActorMethod<[string], [] | [Trek]>,
  'getTreks' : ActorMethod<[], Array<Trek>>,
  'getTreksByState' : ActorMethod<[string], Array<Trek>>,
  'getUgcPhotosByTrek' : ActorMethod<[string], Array<UgcPhoto>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserByReferralCode' : ActorMethod<[string], [] | [UserProfile]>,
  'getWeatherCache' : ActorMethod<[string], [] | [WeatherCache]>,
  'getYatraBySlug' : ActorMethod<[string], [] | [Yatra]>,
  'getYatras' : ActorMethod<[], Array<Yatra>>,
  'initPayment' : ActorMethod<[bigint, bigint, string], Result_7>,
  'processReferral' : ActorMethod<[string], Result_6>,
  'rejectUgcPhoto' : ActorMethod<[string], Result_4>,
  'saveProfile' : ActorMethod<[ProfileInput], Result_2>,
  'setTrailCondition' : ActorMethod<[TrailCondition], Result_5>,
  'setWeatherCache' : ActorMethod<[string, string], undefined>,
  'submitQuery' : ActorMethod<[QueryInput], Result_1>,
  'submitUgcPhoto' : ActorMethod<[UgcPhotoInput], Result_4>,
  'updateBatch' : ActorMethod<
    [bigint, [] | [bigint], [] | [boolean]],
    Result_3
  >,
  'updateBlog' : ActorMethod<[bigint, BlogInput], Result_2>,
  'updateBookingStatus' : ActorMethod<[bigint, string], Result_2>,
  'updateQueryStatus' : ActorMethod<[bigint, string], Result_2>,
  'updateTrek' : ActorMethod<[bigint, TrekInput], Result_2>,
  'validatePromoCode' : ActorMethod<[string], Result_1>,
  'verifyPayment' : ActorMethod<[bigint, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];