/**
 * Shared booking form types, validators, and helpers.
 * @generated by scripts/split-booking-page.mjs — edit here for cross-step logic.
 */
import type { TrekBatchPublic } from "@/backend";
import type { BookableProduct } from "@/lib/booking-product";
import type { DiscountKind } from "@/lib/discount-api";
import { BOOKING_ADD_ONS } from "@/lib/booking-addons";
import { normalizeIndianPhoneDigits } from "@/lib/phone-countries";
import type { BookingFilePayload } from "@/lib/booking-documents";
import { cn } from "@/lib/utils";

export type AppliedCodeDiscount = {
  kind: DiscountKind;
  code: string;
  amount: number;
};

/** 2×2 tap-friendly grid for gender (always boxed, never a single text row). */
export const BOOKING_GENDER_GRID = "booking-gender-grid mt-2";

/** Equal-width Yes / No row */
export const BOOKING_CHOICE_ROW = "booking-choice-row";

/** Contact mode — 2×2 on mobile */
export const BOOKING_CONTACT_GRID = "booking-contact-grid";

/** Single/multi-select pills — uses booking-mobile.css `--active` (wins over base button rules). */
export function bookingChoicePill(active: boolean, compact = false) {
  return cn(
    "booking-choice-pill",
    active && "booking-choice-pill--active",
    compact && "booking-choice-pill--compact",
  );
}

/** Fitness / large option cards */
export function bookingChoiceCard(active: boolean) {
  return cn("booking-choice-card", active && "booking-choice-card--active");
}

/** Checkbox-style selectable rows (dietary, medical) */
export function bookingCheckRow(active: boolean) {
  return cn("booking-check-row", active && "booking-check-row--active");
}

// ── Types ──────────────────────────────────────────────────────────────────

export const CITIES = [
  "Delhi",
  "Mumbai",
  "Pune",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Chandigarh",
  "Dehradun",
  "Other",
];
export const BLOOD_GROUPS = [
  "A+",
  "A-",
  "B+",
  "B-",
  "O+",
  "O-",
  "AB+",
  "AB-",
  "Don't Know",
];
export const MEDICAL_CONDITIONS = [
  { id: "heart", icon: "❤️", label: "Heart condition or High blood pressure" },
  { id: "diabetes", icon: "🩸", label: "Diabetes (Type 1 or Type 2)" },
  { id: "asthma", icon: "🫁", label: "Asthma or respiratory issues" },
  { id: "epilepsy", icon: "🧠", label: "Epilepsy or seizure disorder" },
  { id: "joints", icon: "🦵", label: "Knee, hip, or joint problems" },
  { id: "none", icon: "✅", label: "None of the above" },
];
export const DAYS_OF_WEEK = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export const STEP_LABELS = [
  "Select Date",
  "Your Details",
  "Health Info",
  "Documents",
  "Preferences",
  "Review",
];

export interface CoTraveler {
  name: string;
  age: string;
  gender: string;
  email: string;
  mobile: string;
  relationship: string;
  bloodGroup: string;
  medicalNote: string;
}

export const COMPANION_RELATIONSHIPS = [
  "Spouse / Partner",
  "Family",
  "Friend",
  "Colleague",
  "Other",
] as const;

export const MAX_PARTY_SIZE = 20;

export function emptyCoTraveler(): CoTraveler {
  return {
    name: "",
    age: "",
    gender: "",
    email: "",
    mobile: "",
    relationship: "Friend",
    bloodGroup: "",
    medicalNote: "",
  };
}

/** Manual count on step 1 and/or named companions on step 2 (default: 1). */
export function partyHeadcount(fd: FormDataAccumulated): number {
  return Math.max(fd.groupSize, 1 + fd.coTravelers.length);
}

export function maxCompanionSlots(slotCap?: number): number {
  const cap = slotCap ?? MAX_PARTY_SIZE;
  return Math.max(0, Math.min(MAX_PARTY_SIZE, cap) - 1);
}

export function syncPartyGroupSize(
  fd: FormDataAccumulated,
  slotCap?: number,
): FormDataAccumulated {
  const cap = slotCap ?? MAX_PARTY_SIZE;
  const headcount = Math.min(
    cap,
    Math.max(fd.groupSize, 1 + fd.coTravelers.length),
  );
  return {
    ...fd,
    groupSize: headcount,
    hasCoTravelers: fd.coTravelers.length > 0,
  };
}

export type CoTravelerFieldErrors = Partial<
  Record<keyof CoTraveler, string>
>;

export function validateCoTravelers(fd: FormDataAccumulated): {
  valid: boolean;
  errors: Record<number, CoTravelerFieldErrors>;
  firstMessage: string | null;
} {
  const errors: Record<number, CoTravelerFieldErrors> = {};
  let firstMessage: string | null = null;

  fd.coTravelers.forEach((ct, i) => {
    const row: CoTravelerFieldErrors = {};
    if (!ct.name.trim()) row.name = "Full name is required";
    if (!ct.age.trim()) {
      row.age = "Age is required";
    } else if (Number(ct.age) < 12 || Number(ct.age) > 70) {
      row.age = "Age must be between 12 and 70";
    }
    if (!ct.gender) row.gender = "Please select gender";
    if (ct.email.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(ct.email.trim())) {
      row.email = "Enter a valid email";
    }
    const mobileDigits = normalizeIndianPhoneDigits(ct.mobile);
    if (ct.mobile.trim() && !/^[6-9]\d{9}$/.test(mobileDigits)) {
      row.mobile = "Enter a valid 10-digit mobile number";
    }
    if (Object.keys(row).length > 0) {
      errors[i] = row;
      if (!firstMessage) {
        firstMessage = `Please complete details for person ${i + 2} (${ct.name.trim() || "traveling with you"})`;
      }
    }
  });

  return { valid: !firstMessage, errors, firstMessage };
}

export function normalizeCoTravelers(coTravelers: CoTraveler[]): CoTraveler[] {
  return coTravelers.map((ct) => ({
    ...ct,
    name: ct.name.trim(),
    email: ct.email.trim(),
    mobile: normalizeIndianPhoneDigits(ct.mobile),
    medicalNote: ct.medicalNote.trim(),
  }));
}

export function scrollToFirstCoTravelerError(
  errors: Record<number, CoTravelerFieldErrors>,
) {
  const firstIndex = Object.keys(errors)
    .map(Number)
    .sort((a, b) => a - b)[0];
  if (firstIndex === undefined) return;
  requestAnimationFrame(() => {
    document
      .querySelector<HTMLElement>(
        `[data-booking-companion="${firstIndex}"]`,
      )
      ?.scrollIntoView({ behavior: "smooth", block: "center" });
  });
}

export interface FormDataAccumulated {
  // Step 1
  batchDate: string | null;
  groupSize: number;
  addOns: string[];
  // Step 2
  fullName: string;
  email: string;
  mobile: string;
  whatsappSame: boolean;
  whatsapp: string;
  city: string;
  age: string;
  gender: string;
  emergencyName: string;
  emergencyPhone: string;
  emergencyRelation: string;
  // Step 3
  bloodGroup: string;
  medicalConditions: string[];
  medicalOther: string;
  fitnessLevel: string;
  hasTrekked: boolean;
  longestTrek: string;
  // Step 4
  idProofFile: BookingFilePayload | null;
  photoFile: BookingFilePayload | null;
  fitnessCertFile: BookingFilePayload | null;
  hasCoTravelers: boolean;
  coTravelers: CoTraveler[];
  heardFrom: string;
  // Step 5
  dietary: string[];
  accommodationNote: string;
  needsTransport: boolean;
  transportCity: string;
  transportDate: string;
  contactMode: string[];
  promoCode: string;
  promoApplied: boolean;
  promoDiscount: number;
  otherNotes: string;
  // Step 6
  termsAccepted: boolean;
}

export const DEFAULT_FORM: FormDataAccumulated = {
  batchDate: null,
  groupSize: 1,
  addOns: [],
  fullName: "",
  email: "",
  mobile: "",
  whatsappSame: true,
  whatsapp: "",
  city: "",
  age: "",
  gender: "",
  emergencyName: "",
  emergencyPhone: "",
  emergencyRelation: "",
  bloodGroup: "",
  medicalConditions: [],
  medicalOther: "",
  fitnessLevel: "",
  hasTrekked: false,
  longestTrek: "",
  idProofFile: null,
  photoFile: null,
  fitnessCertFile: null,
  hasCoTravelers: false,
  coTravelers: [],
  heardFrom: "",
  dietary: [],
  accommodationNote: "",
  needsTransport: false,
  transportCity: "",
  transportDate: "",
  contactMode: ["WhatsApp"],
  promoCode: "",
  promoApplied: false,
  promoDiscount: 0,
  otherNotes: "",
  termsAccepted: false,
};

export const BOOKING_DRAFT_KEY = "trekora-booking-draft-v2";

export type Step2FieldKey =
  | "fullName"
  | "email"
  | "mobile"
  | "city"
  | "age"
  | "gender"
  | "emergencyName"
  | "emergencyPhone";

export type Step2FieldErrors = Partial<Record<Step2FieldKey, string>>;

const STEP2_FIELD_ORDER: Step2FieldKey[] = [
  "fullName",
  "email",
  "mobile",
  "city",
  "age",
  "gender",
  "emergencyName",
  "emergencyPhone",
];

export function normalizeStep2Fd(fd: FormDataAccumulated): FormDataAccumulated {
  const mobile = normalizeIndianPhoneDigits(fd.mobile);
  const emergencyPhone = normalizeIndianPhoneDigits(fd.emergencyPhone);
  const whatsapp = fd.whatsappSame
    ? mobile
    : normalizeIndianPhoneDigits(fd.whatsapp);
  return {
    ...fd,
    fullName: fd.fullName.trim(),
    email: fd.email.trim(),
    mobile,
    whatsapp,
    emergencyName: fd.emergencyName.trim(),
    emergencyPhone,
  };
}

export function validateStep2(fd: FormDataAccumulated): {
  valid: boolean;
  errors: Step2FieldErrors;
  firstMessage: string | null;
} {
  const errors: Step2FieldErrors = {};
  if (!fd.fullName.trim()) errors.fullName = "Name is required";
  if (!fd.email.trim()) {
    errors.email = "Email is required";
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fd.email)) {
    errors.email = "Enter a valid email address";
  }
  if (!fd.mobile.trim()) {
    errors.mobile = "Mobile number is required";
  } else if (!/^[6-9]\d{9}$/.test(fd.mobile)) {
    errors.mobile = "Enter a valid 10-digit mobile number";
  }
  if (!fd.city) errors.city = "Please select your city";
  if (!fd.age.trim()) {
    errors.age = "Age is required";
  } else if (Number(fd.age) < 12 || Number(fd.age) > 70) {
    errors.age = "Age must be between 12 and 70";
  }
  if (!fd.gender) errors.gender = "Please select your gender";
  if (!fd.emergencyName.trim()) {
    errors.emergencyName = "Emergency contact name is required";
  }
  if (!fd.emergencyPhone.trim()) {
    errors.emergencyPhone = "Emergency contact number is required";
  } else if (!/^[6-9]\d{9}$/.test(fd.emergencyPhone)) {
    errors.emergencyPhone = "Enter a valid 10-digit emergency number";
  }
  const firstKey = STEP2_FIELD_ORDER.find((k) => errors[k]);
  return {
    valid: !firstKey,
    errors,
    firstMessage: firstKey ? (errors[firstKey] ?? null) : null,
  };
}

export function scrollToFirstStep2Error(errors: Step2FieldErrors) {
  const firstKey = STEP2_FIELD_ORDER.find((k) => errors[k]);
  if (!firstKey) return;
  requestAnimationFrame(() => {
    const el = document.querySelector<HTMLElement>(
      `[data-booking-field="${firstKey}"]`,
    );
    el?.scrollIntoView({ behavior: "smooth", block: "center" });
    const focusable = el?.querySelector<HTMLElement>(
      "input, select, button",
    );
    focusable?.focus({ preventScroll: true });
  });
}

// ── Helpers ────────────────────────────────────────────────────────────────

export function formatINR(n: number) {
  return n.toLocaleString("en-IN");
}

/** Local calendar key YYYY-MM-DD (matches `Date(y,m,d)` cells; avoids UTC-only `new Date("YYYY-MM-DD")` bugs). */
export function formatYmdLocal(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

export function parseYmdLocal(ymd: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(ymd.trim());
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]) - 1;
  const day = Number(m[3]);
  const d = new Date(y, mo, day);
  if (d.getFullYear() !== y || d.getMonth() !== mo || d.getDate() !== day) {
    return null;
  }
  d.setHours(0, 0, 0, 0);
  return d;
}

// INVARIANT: batchDate is epoch milliseconds (ms) from the canister.
// Do NOT divide by 1_000_000 (that would be for nanoseconds). Do NOT multiply on write.
export function formatYmdFromBatchTs(ts: bigint): string {
  const d = new Date(Number(ts));
  if (Number.isNaN(d.getTime())) return "";
  return formatYmdLocal(d);
}

/** Future bookable days in a calendar month (local dates, matches grid). */
export function countFutureAvailableSlotsInMonth(
  viewYear: number,
  viewMonth: number,
  today: Date,
  batchMap: Map<string, TrekBatchPublic>,
): number {
  const dim = new Date(viewYear, viewMonth + 1, 0).getDate();
  let n = 0;
  for (let day = 1; day <= dim; day++) {
    const date = new Date(viewYear, viewMonth, day);
    if (date < today) continue;
    const k = formatYmdLocal(date);
    const batch = batchMap.get(k);
    if (batch && Number(batch.availableSlots) > 0) n++;
  }
  return n;
}

/** Earliest calendar month that still has an active batch on/after `today`. */
export function firstMonthWithFutureBatch(
  batches: TrekBatchPublic[],
  today: Date,
): { y: number; m: number } | null {
  let best: { y: number; m: number; t: number } | null = null;
  for (const b of batches) {
    if (!b.isActive || Number(b.availableSlots) <= 0) continue;
    const d = new Date(Number(b.batchDate));
    if (Number.isNaN(d.getTime())) continue;
    d.setHours(0, 0, 0, 0);
    if (d < today) continue;
    const t = d.getTime();
    if (!best || t < best.t) {
      best = { y: d.getFullYear(), m: d.getMonth(), t };
    }
  }
  return best ? { y: best.y, m: best.m } : null;
}

export type UpcomingBatchChoice = {
  ymd: string;
  batch: TrekBatchPublic;
  slots: number;
};

export function upcomingBatchChoices(
  batches: TrekBatchPublic[],
  today: Date,
  limit = 8,
): UpcomingBatchChoice[] {
  const byDay = new Map<string, TrekBatchPublic>();
  for (const b of batches) {
    if (!b.isActive || Number(b.availableSlots) <= 0) continue;
    const ymd = formatYmdFromBatchTs(b.batchDate);
    if (!ymd) continue;
    const d = parseYmdLocal(ymd);
    if (!d || d < today) continue;
    const prev = byDay.get(ymd);
    if (
      !prev ||
      Number(b.availableSlots) > Number(prev.availableSlots)
    ) {
      byDay.set(ymd, b);
    }
  }
  return [...byDay.entries()]
    .map(([ymd, batch]) => ({
      ymd,
      batch,
      slots: Number(batch.availableSlots),
    }))
    .sort((a, b) => a.ymd.localeCompare(b.ymd))
    .slice(0, limit);
}

export function formatBatchDateLongIN(ymd: string): string {
  const d = parseYmdLocal(ymd);
  if (!d) return ymd;
  return d.toLocaleDateString("en-IN", {
    weekday: "short",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function formatBatchDateShortIN(ymd: string): string {
  const d = parseYmdLocal(ymd);
  if (!d) return ymd;
  return d.toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function generateRef() {
  return `EW-${new Date().getFullYear()}-${Math.random().toString(36).substr(2, 5).toUpperCase()}`;
}

export function calcAddOnsTotal(addOns: string[], groupSize: number) {
  return BOOKING_ADD_ONS.filter((a) => addOns.includes(a.id)).reduce(
    (sum, a) => sum + (a.perPerson ? a.price * groupSize : a.price),
    0,
  );
}

export function calcPrices(
  unitPrice: number,
  groupSize: number,
  addOns: string[],
  promoDiscount: number,
  codeDiscountAmount = 0,
) {
  const base = unitPrice * groupSize;
  const groupDiscount = groupSize >= 5 ? Math.round(base * 0.15) : 0;
  const afterGroup = base - groupDiscount;
  const addOnsTotal = calcAddOnsTotal(addOns, groupSize);
  const subtotal = afterGroup + addOnsTotal;
  const gst = Math.round(subtotal * 0.05);
  const promoSavings = Math.round(subtotal * promoDiscount);
  const preCodeTotal = subtotal + gst - promoSavings;
  const codeSavings = Math.min(
    Math.max(0, Math.round(codeDiscountAmount)),
    preCodeTotal,
  );
  const grandTotal = Math.max(0, preCodeTotal - codeSavings);
  return {
    base,
    groupDiscount,
    afterGroup,
    addOnsTotal,
    subtotal,
    gst,
    promoSavings,
    codeSavings,
    grandTotal,
  };
}
